hwi/HWIOAuthBundle

OAuth/ResourceOwner/FacebookResourceOwner.php, OAuth/ResourceOwner/GoogleResourceOwner.php
If you use facebook or google resource owner, on Symfony 2.6 it was fail
=> Add Symfony 2.6 compatiblity

Security/Core/Authentication/Provider/OAuthProvider.php
This fix prevents locked users (FOSUserBundle) to login with social networks (#528)
=> Check preAuth & postAuth

README.md
=> 0.3 can be used with Symfony 2.6 now

OAuth/ResourceOwner/FacebookResourceOwner.php, Resources/doc/resource_owners/facebook.md, Tests/OAuth/ResourceOwner/FacebookResourceOwnerTest.php
New auth_type as an option parameter to accept re-asking for declined permissions
ping @stloyd
=> Accept auth_type as an option to Facebook OAuth

DependencyInjection/Configuration.php, OAuth/ResourceOwner/FiwareResourceOwner.php, README.md, Resources/config/oauth.xml, Resources/doc/2-configuring_resource_owners.md, Resources/doc/resource_owners/fiware.md, composer.json
I have added and configured a FiwareResourceOwner which supports the FI-WARE Identity Management - KeyRock Service Provider.
=> added support for FI-WARE OAuth2 implementation

OAuth/ResourceOwner/AbstractResourceOwner.php
Fixes #809.
Alternative to: #816, #831
=> Fix issue sending empty content as POST instead of GET

DependencyInjection/Configuration.php, OAuth/ResourceOwner/AzureResourceOwner.php, README.md, Resources/config/oauth.xml, Resources/doc/2-configuring_resource_owners.md, Resources/doc/resource_owners/azure.md, Tests/OAuth/ResourceOwner/AzureResourceOwner.php
Draft for Azure resource owner
I didn't add any tests, coming soon.
=> Azure Resource Owner

OAuth/ResourceOwner/FiwareResourceOwner.php
Add new function getUserInformation and prepare valid data for request with token.
=> Fixed Fiware UserInformation request with active token

OAuth/ResourceOwner/FiwareResourceOwner.php
Bug - missing brackets on line 80 in FiwareResourceOwner.php
=> Fix bug - add missing parenthesis in FiwareResourceOwner.php

OAuth/Exception/HttpTransportException.php, OAuth/ResourceOwner/AbstractResourceOwner.php, Tests/OAuth/ResourceOwner/GenericOAuth2ResourceOwnerTest.php, Tests/OAuth/ResourceOwner/SalesforceResourceOwnerTest.php, Tests/OAuth/ResourceOwner/SinaWeiboResourceOwnerTest.php
This is quite useful to catch these exception.
=> Wrap Buzz exceptions

Connect/AccountConnectorInterface.php
=> Correct doc typo in AccountConnectorInterface.php

OAuth/ResourceOwner/FacebookResourceOwner.php
=> Add fields to infos_url in FacebookResourceOwner

DependencyInjection/Configuration.php, OAuth/ResourceOwner/BufferAppResourceOwner.php, README.md, Resources/config/oauth.xml, Resources/doc/2-configuring_resource_owners.md, Resources/doc/resource_owners/bufferapp.md, Tests/OAuth/ResourceOwner/BufferAppResourceOwnerTest.php, composer.json
Added a BufferApp resource owner.
=> Add BufferApp resource owner.

CHANGELOG.md, Controller/ConnectController.php, DependencyInjection/Configuration.php, DependencyInjection/HWIOAuthExtension.php, Resources/doc/2-configuring_resource_owners.md, Resources/doc/bonus/facebook-connect.md, Resources/doc/internals/reference_configuration.md, Resources/doc/internals/response_object_and_paths.md, Tests/Controller/AbstractConnectControllerTest.php, Tests/DependencyInjection/HWIOAuthExtensionTest.php
Any feedback and help is highly appreciated.
=> Allow multiple firewalls, fixes #496

Tests/OAuth/ResourceOwner/FacebookResourceOwnerTest.php
https://github.com/hwi/HWIOAuthBundle/pull/891
=> update test for #891

Resources/doc/internals/configuring_the_http_client.md
Updating reference configuration to explain proxy usage issue like #869
=> Adding reference configuration for proxy directive in http_client

OAuth/ResourceOwner/InstagramResourceOwner.php
=> Instagram allows only GET to fetch user details

OAuth/ResourceOwner/FacebookResourceOwner.php, OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php
=> Add appsecret_proof for Facebook Resource

OAuth/ResourceOwner/FacebookResourceOwner.php, OAuth/ResourceOwner/GoogleResourceOwner.php, Tests/OAuth/ResourceOwner/FacebookResourceOwnerTest.php
=> Fix token revoking for Facebook & Google resource owners

Resources/doc/2-configuring_resource_owners.md
I've mentioned the CSRF protection mechanism in the documentation
to make it clear that it should be enabled in order to protect
users from that kind of attacks.
=> CSRF protection mentioned in the documentation.

DependencyInjection/Configuration.php, OAuth/ResourceOwner/SlackResourceOwner.php, Resources/config/oauth.xml
Add SlackResourceOwner ; unlinke Evernote's (cf #732), this is kind of easy. For the tests, I was not sure if there was any interest for them, as it is basically OAuth2..
=> Add SlackResourceOwner

OAuth/ResourceOwner/SlackResourceOwner.php, Tests/OAuth/ResourceOwner/SlackResourceOwnerTest.php
=> Add SlackResourceOwner test

CHANGELOG.md, OAuth/ResourceOwner/VkontakteResourceOwner.php, Tests/OAuth/ResourceOwner/GenericOAuth1ResourceOwnerTest.php, Tests/OAuth/ResourceOwner/GenericOAuth2ResourceOwnerTest.php, Tests/OAuth/ResourceOwner/VkontakteResourceOwnerTest.php
=> Fix issues with default scopes & fields for VKontakte resource owner

Resources/doc/resource_owners/discogs.md
The linked documentation about registering your application throws an 404. I have linked to correct URL.
=> Update Discogs Application-URL

OAuth/ResourceOwner/TwitterResourceOwner.php, Resources/doc/resource_owners/twitter.md, Tests/OAuth/ResourceOwner/TwitterResourceOwnerTest.php
=> [Twitter] Provide email from Twitter.

DependencyInjection/HWIOAuthExtension.php
It was creating array of both firewall_names and firewall_name but only firewall_name should be in
=> Typo when merging firewall_names with firewall_name

Resources/doc/4-integrating_fosub.md
=> Syntax error

.travis.yml, CHANGELOG.md, DependencyInjection/HWIOAuthExtension.php, Security/OAuthUtils.php, Tests/Security/OAuthUtilsTest.php
=> List of resource owner maps in OAuthUtils

Controller/ConnectController.php
Missing use of the default_target_path after a successful operation.
Replaces #515.
=> Redirect to target_path after successful registration/connection

DependencyInjection/HWIOAuthExtension.php, Form/FOSUBRegistrationFormHandler.php, Tests/Controller/AbstractConnectControllerTest.php, Tests/Controller/ConnectControllerRegistrationActionTest.php, Tests/Form/FOSUBRegistrationFormHandlerTest.php, Tests/OAuth/ResourceOwner/JiraResourceOwnerTest.php, Tests/Security/OAuthUtilsTest.php, Tests/bootstrap.php
=> Fix problem with handling FOSUser forms & Symfony 3

Security/Core/Authentication/Provider/OAuthProvider.php
Function `$this->hideUserNotFoundExceptions` does not exist.
=> Removed not existing function hideUserNotFoundExceptions

DependencyInjection/Configuration.php, OAuth/ResourceOwner/Office365ResourceOwner.php, Resources/config/oauth.xml, Tests/OAuth/ResourceOwner/Office365ResourceOwnerTest.php
Created Office365 resource owner
=> Office365 resource owner

DependencyInjection/Configuration.php, OAuth/ResourceOwner/ItembaseResourceOwner.php, README.md, Resources/config/oauth.xml, Resources/doc/2-configuring_resource_owners.md, Resources/doc/resource_owners/itembase.md, Tests/OAuth/ResourceOwner/ItembaseResourceOwnerTest.php
Hey!
We are working with HWIOAuthBundle since forever and now wanted to add an itembase ResourceOwner to make it easier to integrate our OAuth flow. :)
=> Added itembase ResourceOwner

DependencyInjection/Configuration.php, OAuth/ResourceOwner/CleverResourceOwner.php, Resources/config/oauth.xml, Resources/doc/2-configuring_resource_owners.md, Resources/doc/resource_owners/clever.md, Tests/OAuth/ResourceOwner/CleverResourceOwnerTest.php, composer.json
First, thanks for creating this bundle!  We've been using this for a while for our Google oAuth, and getting this to work with Clever was a real breeze!
This pull-request adds a ResourceOwner for [Clever](https://clever.com). If there's anything we can do to make this meet your standards, please let us know!
=> Create a CleverResourceOwner

OAuth/ResourceOwner/CleverResourceOwner.php, OAuth/ResourceOwner/GoogleResourceOwner.php, OAuth/ResourceOwner/ItembaseResourceOwner.php, Tests/OAuth/ResourceOwner/GoogleResourceOwnerTest.php
=> Fix for Google "hd" parameter usage with more than one domain

Controller/ConnectController.php
redirectToServiceAction is not redirect, in order to work I have done this change.
=> redirectToServiceAction is not redirecting (SF2 v2.8)

Security/Core/Authentication/Token/OAuthToken.php
=> Make Token un-serializing a bit more smooth when we plan to add more data into it

Templating/Helper/OAuthHelper.php
=> Fallback to empty Request if it was not provider via compiler pass

Controller/ConnectController.php
This bug was introduced in https://github.com/hwi/HWIOAuthBundle/pull/1063
=> Fixed form error in ConnectController

CHANGELOG.md
=> Update change log for 0.5

Controller/ConnectController.php
Reverts hwi/HWIOAuthBundle#1029
Fixes https://github.com/hwi/HWIOAuthBundle/issues/1092
=> Revert "redirectToServiceAction is not redirecting (SF2 v2.8)"

OAuth/ResourceOwner/Office365ResourceOwner.php
Fix https://github.com/hwi/HWIOAuthBundle/issues/1115
=> Fix Office365 path case

composer.json
This should resolve the Symfony 3.2 tests on Travis.
=> Add templating component to composer

.travis.yml
To be merged after https://github.com/hwi/HWIOAuthBundle/pull/1132
=> Add PHP 7.1 to Travis

OAuth/ResourceOwner/OdnoklassnikiResourceOwner.php
*Copy/Paste from VkontakteResourceOwner.php*
Now can change fields of getting user info
[Supported fields](https://apiok.ru/dev/methods/rest/users/users.getCurrentUser)
Configuration:
```yml
hwi_oauth:
resource_owners:
odnoklassniki:
type: odnoklassniki
client_id: '%oauth.ok.client_id%'
client_secret: '%oauth.ok.client_secret%'
authorization_url: 'https://connect.ok.ru/oauth/authorize'
access_token_url: 'https://api.ok.ru/oauth/token.do'
infos_url: 'https://api.ok.ru/fb.do?method=users.getCurrentUser'
scope: 'GET_EMAIL'
options:
application_key: '%oauth.ok.application_key%'
fields: 'uid,birthday,locale,gender,email,first_name,last_name,pic1024x768'
paths:
email: 'email'
firstname: 'first_name'
lastname: 'last_name'
```
=> Add support custom fields for get user info fo Odnoklassniki

Controller/ConnectController.php, Tests/Controller/ConnectControllerConnectActionTest.php
fix error : `The token storage contains no authentication token.` with custom error page #1130
=> Fix error : with custom error page #1130

DependencyInjection/HWIOAuthExtension.php
I'm using the connect functionality without the front-end and that's working pretty well without :)
=> Do not require any form for the connect feature

DependencyInjection/Configuration.php, OAuth/ResourceOwner/GitLabResourceOwner.php, Resources/config/oauth.xml, Resources/doc/2-configuring_resource_owners.md, Resources/doc/resource_owners/gitlab.md, Tests/OAuth/ResourceOwner/GitLabResourceOwnerTest.php, composer.json
#845
reference:
https://docs.gitlab.com/ee/api/oauth2.html
https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples
=> add GitLab resource owner

Controller/ConnectController.php, DependencyInjection/Configuration.php, DependencyInjection/HWIOAuthExtension.php, Resources/config/oauth.xml, Resources/doc/internals/reference_configuration.md, Security/OAuthUtils.php, Tests/Controller/AbstractConnectControllerTest.php, Tests/Security/OAuthUtilsTest.php
=> Allow to change authorization check rule to "IS_AUTHENTICATED_FULLY"

OAuth/ResourceOwner/RedditResourceOwner.php
=> Fixed RedditResourceOwner to use POST while getting token

OAuth/ResourceOwner/AbstractResourceOwner.php, OAuth/ResourceOwner/GenericOAuth1ResourceOwner.php, OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php, Security/Http/Firewall/OAuthListener.php, Security/OAuthErrorHandler.php, Tests/OAuth/ResourceOwner/GenericOAuth2ResourceOwnerTest.php
=> Refactor ResourceOwner error handling into standalone class

OAuth/ResourceOwner/AzureResourceOwner.php, OAuth/ResourceOwner/Bitbucket2ResourceOwner.php, OAuth/ResourceOwner/FiwareResourceOwner.php, OAuth/ResourceOwner/FlickrResourceOwner.php, OAuth/ResourceOwner/GenericOAuth1ResourceOwner.php, OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php, OAuth/ResourceOwner/GitHubResourceOwner.php, OAuth/ResourceOwner/JiraResourceOwner.php, OAuth/ResourceOwner/MailRuResourceOwner.php, OAuth/ResourceOwner/OdnoklassnikiResourceOwner.php, OAuth/ResourceOwner/QQResourceOwner.php, OAuth/ResourceOwner/SinaWeiboResourceOwner.php, OAuth/ResourceOwner/SpotifyResourceOwner.php, OAuth/ResourceOwner/StackExchangeResourceOwner.php, OAuth/ResourceOwner/StereomoodResourceOwner.php, OAuth/ResourceOwner/TraktResourceOwner.php, OAuth/ResourceOwner/VkontakteResourceOwner.php, OAuth/ResourceOwner/WechatResourceOwner.php, OAuth/ResourceOwner/WunderlistResourceOwner.php, OAuth/Response/AbstractUserResponse.php, OAuth/Response/PathUserResponse.php, OAuth/Response/SensioConnectUserResponse.php, OAuth/Response/UserResponseInterface.php, OAuth/ResponseInterface.php, Resources/doc/internals/response_object_and_paths.md, Tests/OAuth/Response/PathUserResponseTest.php
Also `setResponse()` into `setData()`.
Fixes #290.
=> Rename `ResponseInterface` methods `getResponse()` into `getData()`

CHANGELOG.md, OAuth/ResourceOwner/FacebookResourceOwner.php
Fixes https://github.com/hwi/HWIOAuthBundle/issues/1186
=> Update Facebook API to v2.8

Security/Core/Authentication/Provider/OAuthProvider.php, Security/Http/Firewall/OAuthListener.php, Security/Http/ResourceOwnerMap.php, Security/Http/ResourceOwnerMapInterface.php, Security/OAuthUtils.php
I am write a service to Silex, but its does not possible because ResourcrOwnerMap depends Symfony Container.
I added an interface to solve it
=> Add interface to ResourceOwnerMap

CHANGELOG.md, Controller/ConnectController.php, Event/FilterUserResponseEvent.php, Event/FormEvent.php, Event/GetResponseUserEvent.php, Event/UserEvent.php, HWIOAuthEvents.php, Tests/Controller/ConnectControllerConnectServiceActionTest.php, Tests/Controller/ConnectControllerRegistrationActionTest.php
Rebased from https://github.com/hwi/HWIOAuthBundle/pull/1065
=> Added FOSUserBundle like events

HWIOAuthEvents.php
see https://github.com/symfony/symfony/pull/12299 for more information about event annotation
=> Mark event constants with annotation

OAuth/ResourceOwner/AbstractResourceOwner.php, OAuth/ResourceOwner/Auth0ResourceOwner.php, OAuth/ResourceOwnerInterface.php, Tests/OAuth/ResourceOwner/Auth0ResourceOwnerTest.php
Original code done by @glena
Replaces #783
=> Fix Auth0 headers to be more spec compliant

Controller/ConnectController.php, Security/Core/Exception/AccountNotLinkedException.php
Related to fix from: https://github.com/symfony/symfony/pull/4935
=> Fix the `TODO` in `ConnectController` & other small issues in it

DependencyInjection/HWIOAuthExtension.php, Resources/config/http_client.xml, Tests/DependencyInjection/HWIOAuthExtensionTest.php, composer.json
=> Re-use HttpClient DI definition instead of recreating it

Controller/ConnectController.php
An attempt to remove the goto statement in `ConnectController`.
=> Remove goto statement in ConnectController

DependencyInjection/Security/Factory/OAuthFactory.php, Security/Core/Authentication/Provider/OAuthProvider.php, Tests/Security/Core/Authentication/Provider/OAuthProviderTest.php
Solves issue I was having where after 1 hour the token would expire and I would get a redirect loop
=> Refresh token functionality

Resources/doc/1-setting_up_the_bundle.md
- Replaced setup it with set it up.
- Replaced this permit by this makes it possible.
- Replaced "with help by" by thanks to.
=> Minor grammar edits

Security/Core/Authentication/Provider/OAuthProvider.php
=> Fix token reloading on each isGranted call

OAuth/ResourceOwner/RedditResourceOwner.php
Fix an error on header, without this generated header is '0: Authorization: Basic RVF...'
=> Fix error on reddit provider

DependencyInjection/HWIOAuthExtension.php
At S4 all services are private by default
=> #1308 Make resource owner public

Resources/doc/internals/configuring_the_http_client.md
I discovered this issue while installing the bundle from scratch.
=> Fix docs about manual HTTPlug configuration

README.md
https://github.com/hwi/HWIOAuthBundle/blob/0.6.1/composer.json#L96-L101
=> Version 0.6 requires Symfony 2.8 or higher

OAuth/ResourceOwner/LinkedinResourceOwner.php, Tests/OAuth/ResourceOwner/LinkedinResourceOwnerTest.php
Hello,
I added firstname and lastname for LinkedinResourceOwner
Here the [documentation](https://developer.linkedin.com/docs/fields/basic-profile)
=> Add firstname and lastname on LinkedIn

Resources/config/routing/connect_41.xml, Resources/config/routing/login_41.xml, Resources/config/routing/redirect_41.xml, Resources/doc/1-setting_up_the_bundle.md
Replaces https://github.com/hwi/HWIOAuthBundle/pull/1391
=> Add Symfony 4.1 routing files

OAuth/ResourceOwner/VkontakteResourceOwner.php
Replaces https://github.com/hwi/HWIOAuthBundle/pull/1255
=> Fix Vkontakte nickname path

OAuth/ResourceOwner/WindowsLiveResourceOwner.php
Fixes https://github.com/hwi/HWIOAuthBundle/issues/1359
Fixes https://github.com/hwi/HWIOAuthBundle/issues/1346
Replaces https://github.com/hwi/HWIOAuthBundle/pull/1352
=> Windows Live resource owner fix

Controller/ConnectController.php
=> [Bugfix] Don't start session when already initialized & start if not started yet

Resources/doc/3-configuring_the_security_layer.md
Add note on how to configure the templating layer to let the user choose social login
=> Add note on how to configure the templating layer

OAuth/ResourceOwner/WindowsLiveResourceOwner.php
Update WindowsLive Resource Owner to include first and last name.
Fix Token Request require Content-Type to be set to form type.
=> Fix for #1425 and #1428 and #692

Tests/Controller/AbstractConnectControllerTest.php, Tests/Controller/ConnectControllerConnectServiceActionTest.php, Tests/Controller/ConnectControllerRegistrationActionTest.php, Tests/DependencyInjection/HWIOAuthExtensionTest.php, Tests/Fixtures/MyCustomProvider.php, Tests/Form/FOSUBRegistrationFormHandlerTest.php, Tests/OAuth/ResourceOwner/GenericOAuth1ResourceOwnerTest.php, Tests/OAuth/ResourceOwner/GenericOAuth2ResourceOwnerTest.php, Tests/OAuth/ResourceOwner/ResourceOwnerTestCase.php, Tests/OAuth/Response/PathUserResponseTest.php, Tests/Security/Core/Authentication/Provider/OAuthProviderTest.php, Tests/Security/Core/Authentication/Token/OAuthTokenTest.php, Tests/Security/Core/User/EntityUserProviderTest.php, Tests/Security/Core/User/FOSUBUserProviderTest.php, Tests/Security/Core/User/OAuthUserProviderTest.php, Tests/Security/OAuthUtilsTest.php, composer.json
Port of https://github.com/hwi/HWIOAuthBundle/pull/1463/commits/bdf01ae429adb6756312b14ed96014d6c5fcf391
=> Update tests to new PHPUnit standards

CHANGELOG.md, Resources/config/http_client.xml
It's not being called in the controller anyway.
=> Make HttpMethodsClient service private

Resources/doc/resource_owners/windows_live.md
=> Update windows_live.md: broken url fix

Controller/ConnectController.php, DependencyInjection/CompilerPass/ResourceOwnerMapCompilerPass.php, HWIOAuthBundle.php, Resources/config/controller.xml, Resources/config/oauth.xml, Security/Http/ResourceOwnerMapLocator.php, Tests/Controller/AbstractConnectControllerTest.php
Fixes https://github.com/hwi/HWIOAuthBundle/issues/1516
=> Introduce ResourceOwnerMapLocator

OAuth/ResourceOwner/LinkedinResourceOwner.php
This got my setup with linkedin to work
=> Add missing client options in doGetTokenRequest for linkedin

OAuth/ResourceOwner/AbstractResourceOwner.php, OAuth/ResourceOwner/LinkedinResourceOwner.php
=> Fixed LinkedIn resource owner to always put `Content-Length` header in POST requests

OAuth/ResourceOwner/SensioConnectResourceOwner.php, Tests/OAuth/ResourceOwner/SensioConnectResourceOwnerTest.php
Fix https://github.com/hwi/HWIOAuthBundle/issues/1564
=> Fix wrong default config for symfony connect

OAuth/ResourceOwner/InstagramResourceOwner.php, Resources/doc/resource_owners/instagram.md, Tests/OAuth/ResourceOwner/InstagramResourceOwnerTest.php
Refactor InstagramResourceOwner compliant with Instagram Basic Display API
Fix: #1558
=> Instagram Basic Display API

OAuth/ResourceOwner/VkontakteResourceOwner.php
Fixes #1559 
Disabled `use_authorization_to_get_token`.
=> Fix: Vkontakte owner

OAuth/ResourceOwner/SensioConnectResourceOwner.php
After some changes on SfConnect side, we need to update the sensio resource owner.
This is part of #SymfonyHackday
=> Fix Symfony Connect resource owner

Tests/Controller/AbstractConnectControllerTest.php, Tests/Controller/LoginControllerTest.php, Tests/Controller/RedirectToServiceControllerTest.php, Tests/DependencyInjection/HWIOAuthExtensionTest.php, Tests/OAuth/ResourceOwner/CleverResourceOwnerTest.php, Tests/OAuth/ResourceOwner/GenericOAuth1ResourceOwnerTest.php, Tests/OAuth/ResourceOwner/GenericOAuth2ResourceOwnerTest.php, Tests/OAuth/ResourceOwner/SensioConnectResourceOwnerTest.php, Tests/OAuth/Response/PathUserResponseTest.php, Tests/Security/Core/Authentication/Token/OAuthTokenTest.php, Tests/Security/Core/User/EntityUserProviderTest.php, Tests/Security/Core/User/FOSUBUserProviderTest.php, Tests/Security/Core/User/OAuthUserProviderTest.php, Tests/Security/Core/User/OAuthUserTest.php, composer.json
And remove PHPUnit 6 as it is no longer supported.
=> Add PHPUnit 8

README.md
=> Update to latest release 1.1

Controller/ConnectController.php, Event/FilterUserResponseEvent.php
Returns the response of FilterUserResponseEvent event in registrationAction of LoginController and to do so adds a setResponse to the event to be able to change it.
This lets customize response after "authenticateUser()".
=> Adds ability to change response in FilterUserResponseEvent

DependencyInjection/Configuration.php, OAuth/ResourceOwner/KeycloakResourceOwner.php, Resources/config/oauth.xml, Resources/doc/2-configuring_resource_owners.md, Resources/doc/resource_owners/keycloak.md, Tests/OAuth/ResourceOwner/KeycloakResourceOwnerTest.php
- changed behaviour and automatic url creation
- added dependency
- changed test
- added documentation
=> Make Keycloak work like other resource owners

DependencyInjection/Configuration.php, OAuth/ResourceOwner/InstagramResourceOwner.php, Tests/OAuth/ResourceOwner/InstagramResourceOwnerTest.php
- Update InstagramResourceOwner
- Extend configuration with use_authorization_to_get_token option
=> Fixes for #1635 and #1636

DependencyInjection/Configuration.php, OAuth/ResourceOwner/AppleResourceOwner.php, README.md, Resources/config/oauth.xml, Resources/doc/2-configuring_resource_owners.md, Resources/doc/resource_owners/apple.md, Tests/OAuth/ResourceOwner/AppleResourceOwnerTest.php, composer.json
-Implemented Apple Sign In
-Added Test Case
-Thanks to @BourotBenjamin and @kevinpapst who made base implemenation and base test case.
=> Apple Sign in Support

Security/Core/User/EntityUserProvider.php, Tests/Security/Core/User/EntityUserProviderTest.php
Very simple fix for doctrine/persistence which is now ^2.0
=> doctrine persistence deprecation fix

Controller/ConnectController.php
Fix for issue https://github.com/hwi/HWIOAuthBundle/issues/1662
=> ConnectController::getParameter() is considered final deprecation fix

composer.json
=> Allow using bundle on PHP 8

.php-cs-fixer.php, composer.json
=> bump php-cs-fixer to ^3.0

DependencyInjection/Configuration.php
Not needed anymore since we dropped support for those Symfony versions.
=> remove BC layer for older Symfony versions

Security/OAuthUtils.php, Tests/Security/OAuthUtilsTest.php
I've added support for state parameters directly into `OAuthUtils`.
=> Added state support for service authentication URLs

.github/workflows/ci.yaml, Tests/Controller/ConnectControllerConnectServiceActionTest.php, Tests/Controller/ConnectControllerRegistrationActionTest.php, Tests/OAuth/ResourceOwner/GenericOAuth1ResourceOwnerTest.php, Tests/OAuth/ResourceOwner/JiraResourceOwnerTest.php, composer.json, phpunit.xml.dist
Backporting for `1.4` release.
=> Maintain | Upgrade PHPUnit to 9.5

DependencyInjection/Security/Factory/OAuthAuthenticatorFactory.php, HWIOAuthBundle.php, Security/Http/Authenticator/OAuthAuthenticator.php, Tests/Security/Http/Authenticator/OAuthAuthenticatorTest.php
=> Support Symfony new Authenticator-based security system

Security/Core/Authentication/Provider/OAuthProvider.php, Tests/Security/Core/Authentication/Provider/OAuthProviderTest.php
=> Rework security OAuthProvider to properly refresh data inside tokens

CHANGELOG.md, Controller/ConnectController.php, Controller/LoginController.php, OAuth/RequestDataStorage/SessionStorage.php, Resources/config/controller.xml, Resources/config/oauth.xml, Tests/Controller/AbstractConnectControllerTest.php, Tests/Controller/LoginControllerTest.php, Tests/Functional/Controller/ConnectControllerTest.php, Tests/Functional/Controller/LoginControllerTest.php, Tests/OAuth/RequestDataStorage/SessionStorageTest.php
=> Fix deprecation of SessionInterface as service

Security/Core/Authentication/Provider/OAuthProvider.php, Tests/Security/Core/Authentication/Provider/OAuthProviderTest.php
=> Force token refresh if authenticated token was expired already

.github/workflows/ci.yaml, Makefile, Tests/App/AppKernel.php, Tests/App/security.php, Tests/Functional/Controller/ConnectControllerTest.php, composer.json, phpstan.neon
Related to https://github.com/hwi/HWIOAuthBundle/issues/1737
This adds very basic phpstan analysis with level 1.
Level 2 has 94 errors and could be done in a follow-up PR
=> add phpstan with level 1

Controller/ConnectController.php, DependencyInjection/Configuration.php, DependencyInjection/Security/Factory/OAuthFactory.php, HWIOAuthBundle.php, OAuth/Response/LinkedinUserResponse.php, OAuth/Response/SensioConnectUserResponse.php, Security/Core/Exception/AccountNotLinkedException.php, Security/Http/Authenticator/OAuthAuthenticator.php, Security/Http/EntryPoint/OAuthEntryPoint.php, Tests/Controller/AbstractConnectControllerTest.php, Tests/Controller/ConnectControllerRegistrationActionTest.php, Tests/DependencyInjection/HWIOAuthExtensionTest.php, Tests/OAuth/ResourceOwner/GenericOAuth1ResourceOwnerTest.php, Tests/OAuth/ResourceOwner/GenericOAuth2ResourceOwnerTest.php, Tests/OAuth/ResourceOwner/JiraResourceOwnerTest.php, Tests/OAuth/ResourceOwner/LinkedinResourceOwnerTest.php, Tests/OAuth/ResourceOwner/QQResourceOwnerTest.php, Tests/Security/Core/Authentication/Provider/OAuthProviderTest.php, Tests/Security/Core/User/EntityUserProviderTest.php, Tests/Security/Http/Authenticator/OAuthAuthenticatorTest.php, composer.json, phpstan.neon
Follow-up for https://github.com/hwi/HWIOAuthBundle/pull/1742 and part of https://github.com/hwi/HWIOAuthBundle/issues/1737
=> increase phpstan to level 2

DependencyInjection/Security/Factory/OAuthFactory.php
https://github.com/hwi/HWIOAuthBundle/blob/1.4/DependencyInjection/Security/Factory/OAuthAuthenticatorFactory.php is extending it
=> Remove `@final` from OAuthFactory

.gitattributes
This allows to reduce zip files & save some MB sent over network, let's "save" some 🌳 🌳 🌳
=> Maintain | Add `.gitattributes` to remove useless files from zip archives

.github/workflows/ci.yaml, CHANGELOG.md, composer.json
Fixes https://github.com/hwi/HWIOAuthBundle/issues/1744
=> Bump minimal PHP version to 7.4

Security/Core/User/FOSUBUserProvider.php
=> Remove "final" parameter from `FOSUBUserProvider`

.github/workflows/ci.yaml, composer.json
Requires: https://github.com/phpspec/prophecy/issues/531
=> Maintain | Added PHP 8.1 to testing matrix

Resources/config/oauth.xml, Security/Http/Firewall/OAuthListener.php
=> Bugfix | Remove "abstract=true" from non-abstract service definitions

OAuth/ResourceOwner/YahooResourceOwner.php, Resources/doc/resource_owners/yahoo.md, Tests/OAuth/ResourceOwner/YahooResourceOwnerTest.php
=> Update Yahoo resource owner to use OAuth2

.github/workflows/ci.yaml, composer.json, phpunit.xml.dist
The idea is to show all deprecations warnings and fix them
=> Test with Symfony 5.4

.github/workflows/ci.yaml, DependencyInjection/Security/Factory/OAuthAuthenticatorFactory.php, Security/Http/Authenticator/OAuthAuthenticator.php, Security/Http/EntryPoint/OAuthEntryPoint.php, Security/Http/Firewall/OAuthListener.php, Tests/App/AppKernel.php, Tests/App/config/security_v5_bc.yaml, Tests/App/config/security_v6.yaml, Tests/Security/Http/Authenticator/OAuthAuthenticatorTest.php
=> Bugfix | Test BC layer for Symfony Security <5.4

Security/Http/Authenticator/OAuthAuthenticator.php
=> Bugfix | Added missing `RememberMeBadge` into OAuth passport

Resources/config/routing/connect.xml, Resources/config/routing/login.xml, Resources/config/routing/redirect.xml
=> Force particular methods on internal routes

src/Resources/config/util.xml
=> Track oauth requests by symfony-profiler

composer.json
=> Http client for symfony 4.4

src/OAuth/ResourceOwner/KeycloakResourceOwner.php
=> Keycloak: default paths mapping for a new created keycloak realm

CHANGELOG.md, src/Security/Http/Authenticator/OAuthAuthenticator.php, tests/Fixtures/CustomEventListener.php, tests/Functional/IntegrationTest.php
=> Bugfix: InteractiveLoginEvent Event will be triggered also for OAuthAuthenticator

src/DependencyInjection/Configuration.php
phpstan does not moan to ifEmpty anymore.
=> Improve Configuration.php readability

OAuth/ResourceOwner/AppleResourceOwner.php, OAuth/Response/SensioConnectUserResponse.php, Security/Http/Authenticator/OAuthAuthenticator.php
=> Bugfix | Added missing RememberMeBadge into OAuth passport

docs/resource_owners/keycloak.md, src/OAuth/ResourceOwner/KeycloakResourceOwner.php, tests/OAuth/ResourceOwner/KeycloakResourceOwnerTest.php
I added this feature to auto redirect to a specific IDP when there are multiple options available.
=> Added feature to auto hint towards specific idp

src/Controller/Connect/RegisterController.php, src/Controller/RedirectToServiceController.php, src/DependencyInjection/CompilerPass/RefreshOAuthTokenCompilerPass.php, src/DependencyInjection/Configuration.php, src/OAuth/ResourceOwner/AbstractResourceOwner.php, src/OAuth/Response/AbstractUserResponse.php, src/OAuth/State/State.php, src/Security/Core/User/EntityUserProvider.php, src/Security/Http/Authenticator/OAuthAuthenticator.php, src/Security/OAuthUtils.php, src/Test/OAuth/ResourceOwner/GenericOAuth2ResourceOwnerTestCase.php, src/Test/OAuth/ResourceOwner/ResourceOwnerTestCase.php, src/Twig/Extension/OAuthRuntime.php
- Run PHP-CS-Fixer
- Fix new PHPStan issues
=> Fix CS and PHPStan

Resources/doc/resource_owners/azure.md
[Azure] Mention the mandatory parameter `scope`.
I'm not sure that the `".default"` is universal, and don't know how to guide for more specific values.
=> [Azure] Mention the mandatory parameter `scope`.

README.md, docs/2-configuring_resource_owners.md, docs/resource_owners/passage.md, src/OAuth/ResourceOwner/PassageResourceOwner.php, tests/OAuth/ResourceOwner/PassageResourceOwnerTest.php
I missed an implementation of [Passage](https://passage.1password.com/) from 1Password that supports [Passkeys](https://passkeys.directory/).
=> Add resource owner Passage

src/DependencyInjection/Configuration.php
Backport of the fix https://github.com/hwi/HWIOAuthBundle/pull/1879  for branch 2.0
=> Allow "use_authorization_to_get_token" to be configured to false for generic OAuth2

src/OAuth/ResourceOwner/FacebookResourceOwner.php
=> Update API version for Facebook to latest available

src/Controller/RedirectToServiceController.php, src/DependencyInjection/Security/Factory/OAuthAuthenticatorFactory.php, src/Resources/config/oauth.php, src/Security/Core/User/EntityUserProvider.php, src/Security/Http/Authentication/AuthenticationFailureHandler.php, src/Security/Http/Authenticator/OAuthAuthenticator.php, src/Security/Http/EntryPoint/OAuthEntryPoint.php, src/Security/Http/Firewall/RefreshAccessTokenListenerOld.php, src/Security/Http/ResourceOwnerMap.php, src/Security/OAuthErrorHandler.php, src/Security/OAuthUtils.php, tests/Security/Http/Authentication/AuthenticationFailureHandlerTest.php, tests/Security/Http/RefreshOnExpireTest.php
=> Replace custom authenticator passport with custom badge usage

src/Controller/Connect/RegisterController.php
In the registration process the refresh token is being lost.
=> Don't miss refresh token

src/Controller/Connect/RegisterController.php
=> Allow `null` as `$registrationForm` in `RegisterController`

docs/4-configuring_the_connect.md
In this example, we don't have any idea which interface should be used, I added them to avoid spending hours (in some IDE we don't have auto import)
=> Docs: Update 4-configuring_the_connect.md

src/Security/Http/Firewall/RefreshAccessTokenListener.php
Should fix https://github.com/hwi/HWIOAuthBundle/issues/2018
=> fix: incompatibility with Symfony 7.2

src/OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php
for more details see https://github.com/hwi/HWIOAuthBundle/issues/2002
=> add client id/secret to the MS live request body
