Resources/doc/bonus/facebook-connect.md

Display option is required. An error occurs if the display option is not defined ("The option "display" with value null is invalid. Accepted values are: "page", "popup", "touch".").

Display option added

---

Security/Core/Authentication/Token/OAuthToken.php

Hi there,
I need to persist the OAuthToken in database, and I'd like to only persist `rawToken` information to avoid unnecessary user serialization.
I need to do so to be able to re-inject a createdAt value in a freshly created OAuthToken object.
Can I also create another PR where variables are `protected` and not `private` to be able to extend more easily the OAuthToken class?
Thanks a lot
Best

Add getter / setter for OAuthToken createdAt property

---

OAuth/ResourceOwner/FacebookResourceOwner.php
OAuth/ResourceOwner/GoogleResourceOwner.php
Tests/OAuth/ResourceOwner/DailymotionResourceOwnerTest.php
Tests/OAuth/ResourceOwner/FacebookResourceOwnerTest.php
Tests/OAuth/ResourceOwner/GenericOAuth1ResourceOwnerTest.php
Tests/OAuth/ResourceOwner/GenericOAuth2ResourceOwnerTest.php
Tests/OAuth/ResourceOwner/GoogleResourceOwnerTest.php

Hi guys!
This is a cherry-pick of sha: 9186f9299d291f113d3f1bb63067349cb6d6ff81, which was applied to the master branch only. The issue is that we need a new 0.3 tag, so I'm backporting this for that reason.
This will be the *only* commit that's on the `0.3` branch, so tagging it should be easy.
But, master has a lot of commits - @stloyd what's the plan for the `0.4` release?
Thanks!

Backport 2.6 compat to 0.3 + we need a tag

---

Resources/config/routing/connect.xml
Resources/config/routing/login.xml
Resources/config/routing/redirect.xml
Resources/doc/3-configuring_the_security_layer.md
Resources/doc/bonus/facebook-connect.md
Resources/doc/internals/reference_configuration.md

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |
Replaces arguments which are deprecated from Symfony 2.2:
Before:
```xml
<route id="hwi_oauth_connect_registration" pattern="/registration/{key}">
<default key="_controller">HWIOAuthBundle:Connect:registration</default>
</route>
```
After:
```xml
<route id="hwi_oauth_connect_registration" path="/registration/{key}">
<default key="_controller">HWIOAuthBundle:Connect:registration</default>
</route>
```

Replaced routing deprecated arguments

---

DependencyInjection/Configuration.php
OAuth/ResourceOwner/SpotifyResourceOwner.php
README.md
Resources/config/oauth.xml
Resources/doc/2-configuring_resource_owners.md
Resources/doc/resource_owners/spotify.md
Tests/OAuth/ResourceOwner/SpotifyResourceOwnerTest.php
composer.json

Adds a new ```ResourceOwner``` for Spotify following OAuth2 integration from [authorization guide] (https://developer.spotify.com/web-api/authorization-guide)

Add resource owner for Spotify

---

Security/Core/User/FOSUBUserProvider.php

In this class $reloadedUser is used, which is not defined. It should be $user.

Fixed FOSUBUserProvider refreshUser

---

Security/Core/User/FOSUBUserProvider.php
composer.json

Should fix #691.
@fracsi @dincho @regularjack @dupuchba can you please confirm it?
ping @stloyd => This is for `0.3`.

Get back symfony/property-access 2.3 BC

---

CHANGELOG.md
OAuth/ResourceOwner/EventbriteResourceOwner.php
OAuth/ResourceOwner/FoursquareResourceOwner.php
OAuth/ResourceOwner/HubicResourceOwner.php
OAuth/ResourceOwner/ThirtySevenSignalsResourceOwner.php
OAuth/ResourceOwner/ToshlResourceOwner.php
OAuth/ResourceOwner/VkontakteResourceOwner.php
OAuth/ResourceOwner/XingResourceOwner.php
OAuth/Response/PathUserResponse.php
OAuth/Response/SensioConnectUserResponse.php
OAuth/Response/UserResponseInterface.php
Tests/Fixtures/CustomUserResponse.php
Tests/OAuth/ResourceOwner/EventbriteResourceOwnerTest.php
Tests/OAuth/ResourceOwner/FoursquareResourceOwnerTest.php
Tests/OAuth/ResourceOwner/HubicResourceOwnerTest.php
Tests/OAuth/ResourceOwner/ThirtySevenSignalsResourceOwnerTest.php
Tests/OAuth/ResourceOwner/ToshlResourceOwnerTest.php
Tests/OAuth/ResourceOwner/XingResourceOwnerTest.php
Tests/OAuth/Response/PathUserResponseTest.php

Many providers has first name and last name fields that could be very interesting to get separately on our applications.
This PR adds `getFirstName` and `getLastName` on `UserResponseInterface` and his children classes.
Concerned resource owners are also updated.

Add first and last names on OAuth responses

---

OAuth/ResourceOwner/BitlyResourceOwner.php

curl -H 'Authorization: Bearer 12345' 'https://api-ssl.bitly.com/v3/user/info?format=json'
{"status_code": 500, "data": null, "status_txt": "MISSING_ARG_ACCESS_TOKEN"}

the bitly v3 user info does not support bearer tokens

---

OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php

If we deactivate the option use_bearer_authorization, and use a set of parameters instead, the httpRequest did not receive these parameters as they aren't used

Spread the $parameters argument to the httpRequest call

---

Resources/doc/1-setting_up_the_bundle.md

The previous instruction were incomplete, as they are missing the actual installation.

Update the Composer instruction

---

Controller/ConnectController.php

I needed to access the service in the connection-success view (after I'd overridden it). Seems useful?

Pass the service name to the success view as well

---

Resources/doc/resource_owners/jira.md

Private key as string does not work. OAuthUtils always does file_get_contents()

[DX] Add hint on base url and private key

---

Security/Core/User/EntityUserProvider.php
Tests/Security/Core/User/EntityUserProviderTest.php

When using the Oro Platform (or sub-products, like OroCRM), the entity manager is overridden at runtime in order to add dynamic fields to entities (via configuration).
However, if a repository is fetched in the constructor of a service (like it was the case here), the repository does not yet have this runtime magic applied and it breaks the application.
This commit is meant to delay the fetching of the repository to the last possible moment (when querying for users), so that the kernel loading process does not break applications. Moreover, I think removing as much logic as possible from the constructor is a good idea overall.

Avoid logic to be executed at class initialization

---

Security/Core/User/FOSUBUserProvider.php

This lets me override parts of the code to add token-storage without having to copy paste the whole connect logic:
```php
class UserProvider extends FOSUBUserProvider
{
public function loadUserByOAuthUserResponse(UserResponseInterface $response)
{
$user = parent::loadUserByOAuthUserResponse($response);
$user->setGithubToken($response->getAccessToken());
return $user;
}
public function disconnect(UserInterface $user)
{
$user->setGithubToken(null);
parent::disconnectUser($user);
}
}
```

Extract method to disconnect users

---

OAuth/Response/AbstractUserResponse.php
OAuth/Response/UserResponseInterface.php

When connecting to Google one want to get access to the raw token which is in the OAuthToken, to be able to verify it.
I didn't find a way to do that in `OAuthAwareUserProviderInterface::loadUserByOAuthUserResponse(UserResponseInterface $response)`, thus adding a getter.

Add getter for oAuthToken

---

OAuth/ResourceOwner/GenericOAuth1ResourceOwner.php
Tests/OAuth/ResourceOwner/GenericOAuth1ResourceOwnerTest.php

As it's done into `GenericOAuth2ResourceOwner` (https://github.com/hwi/HWIOAuthBundle/blob/master/OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php#L160-L164), `InvalidArgumentException` thrown by the storage should be catched and transformed into `AuthenticationException`.

Catch InvalidArgumentException from storage

---

DependencyInjection/Configuration.php

Adding this flag, now are able to rewrite default parameters.\
For example, in HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\GitHubResourceOwner there is a custom parameter *emails_url* that's not defined in the configuration tree builder. (Maybe other OAuth providers has another custom parameters)
Now, the GitHub Resource is fully compatible with GitHub Enterprise adding this in the main project config.yml
``` yml
hwi_oauth:
...
resource_owners:
github:
type:          github
client_id:     %github.client_id%
client_secret: %github.client_secret%
authorization_url: %github.authorization_url%
access_token_url: %github.access_token_url%
revoke_token_url: %github.revoke_token_url%
infos_url: %github.infos_url%
emails_url: %github.emails_url%
```

Ignore custom keys to be able to rewrite any default parameter.

---

OAuth/ResourceOwner/GoogleResourceOwner.php
Tests/OAuth/ResourceOwner/GoogleResourceOwnerTest.php

Google OAuth response provides both first name and last name as `given_name` and `family_name` respectively

Add paths for first name and last name

---

Controller/ConnectController.php
DependencyInjection/HWIOAuthExtension.php
Security/Http/ResourceOwnerMap.php
Tests/DependencyInjection/HWIOAuthExtensionTest.php

Use `isset()` instead of `in_array()` to check existence of resource owner.
Replaces #907.

Use ContainerAwareInterface in resource map

---

Tests/Security/Core/Authentication/Token/OAuthTokenTest.php

Add missing test for OAuthToken::isExpired() method

---

Controller/ConnectController.php
DependencyInjection/Configuration.php
DependencyInjection/HWIOAuthExtension.php
Tests/DependencyInjection/HWIOAuthExtensionTest.php

i. e. if user denies authentication via resource owner.
Replaces #724. Fixes #363.

Configurable redirect when connecting accounts failed

---

Resources/doc/internals/reference_configuration.md

Fix reference documentation for OAuth2, according to https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/resource_owners/others.md#oauth2

Fix reference documentation for OAuth2

---

OAuth/ResourceOwner/SalesforceResourceOwner.php

Proposed change corrects a bug that avoids to transform "https://login.salesforce.com/" in "https://test.salesforce.com/"

correct wrong preg_replace

---

.travis.yml
CHANGELOG.md
composer.json

To match discussion around PRs/issues, i.e.: #808.
We go to mark version `0.5` (current master) as compatible with Symfony 3.

[0.4] Remove testing support for Symfony 3 in version 0.4

---

Resources/doc/internals/response_object_and_paths.md

I was at the edge of madness when I discovered the problem: we have to call LI using https, not http.

Incorrect schema for infos_url parameter

---

DependencyInjection/Configuration.php
OAuth/ResourceOwner/Bitbucket2ResourceOwner.php
OAuth/ResourceOwner/BitbucketResourceOwner.php
Resources/config/oauth.xml

Add new provider (class) to use BitBucket OAuth2 provider implementation.
This provider is able to get email address (OAuth1 provider is not able to actually).
To use it you will need to specify ```bitbucket2```

BitBucket OAuth2 implementation 

---

OAuth/ResourceOwner/DiscogsResourceOwner.php

Asked by @XWB in #993 
According to this API announcement 25 days ago https://www.discogs.com/forum/thread/347984#7056344
API must use https instead of http, or oAuth will not work
Fix #992

Change Discogs URL from http to https

---

OAuth/ResourceOwner/FacebookResourceOwner.php

Facebook Graph API on version `v2.0` will be closed on 8th August. This pull request bumps API version to `v2.3`. 
I know that there is `v2.6` already available, but since `v2.4` amount of data returned by `/me` is greatly reduced to only:
- name
- user id
So refactoring to use `>=v2.4` would be more time consuming. Treat this Pull Request as a hotfix.

Bumped Facebook Resource Owner version to use API v2.3

---

Resources/doc/1-setting_up_the_bundle.md

Prevent routing error message :
Unable to generate a URL for the named route "hwi_oauth_connect_service" as such route does not exist.

Prevent routing error message

---

OAuth/ResourceOwner/FacebookResourceOwner.php

New apps on facebook can _only_ use the newest api. 
So now, the bundle does not work for app younger than eg a year.

update to facebook api v2.7

---

Security/OAuthUtils.php

Like @xaben said in https://github.com/hwi/HWIOAuthBundle/issues/607
The option "auth_with_one_url" is set to true, but appending `?authenticated=true` essentially breaks the whole point in this option as the URL is different.
For example:
Soundcloud accept only one redirect url; Adding `authenticated=true` to the url when the user is authenticated make this url invalid because it is different from the unauthenticated version.

Remove authenticated=true

---

OAuth/ResourceOwner/FiwareResourceOwner.php

OptionsResolver setNormalizers has been removed in Symfony 3.0. Added compatibility fix to Fiware Resource Owner to make it compatible with Symfony 3.

Symfony 3 compatibility fix to Fiware Resource Owner.

---

Controller/ConnectController.php

if user has already authenticated by OAuthToken and is connecting to a new OAuth account we need to pass the new access token to authenticateUser method. Another case after page reload we have old access token and new resource owner name in OAuthToken.

pass new accessToken to the authenticateUser method

---

OAuth/ResourceOwner/WechatResourceOwner.php

WeChat has a different  url for refresh token, check this [link](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419316505&token=&lang=zh_CN) if necessary.

correct refresh token for WeChat

---

Controller/ConnectController.php
DependencyInjection/HWIOAuthExtension.php

Accessing type "form" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\FormType" instead.

Resolved deprecated messages

---

OAuth/ResourceOwner/WechatResourceOwner.php

if return HttpMessageInterface $response,  when ( throw new AccountNotLinkedException() ), will not be able to use it properly.

object cann't serialize/unserialize

---

Controller/ConnectController.php

The legacy check is done the same way as it is done in FOSUserBundle.

Fixed Symfony3 compatibility in ConnectController::connectServiceAction

---

OAuth/ResourceOwner/TrelloResourceOwner.php
Resources/doc/resource_owners/trello.md
Tests/OAuth/ResourceOwner/TrelloResourceOwnerTest.php

Hi there,
As mentioned in #794, #434, Trello provider does not work anymore.
Some points:
- Trello is returning a 500 status code if `realm` is given in `/OAuthGetRequestToken` headers. In fact, [that line](https://github.com/hwi/HWIOAuthBundle/blob/master/OAuth/ResourceOwner/GenericOAuth1ResourceOwner.php#L195) adds a default realm if not specified (or `null` or `false` which is more serious, a stricter check should be done here, but that is another story). Passing a bullshit realm fixes the 500 and makes the integration work again
- Trello does not return (anymore?) an `_id`. Switched to `id`
- Finally, I added the ability to pass some very important options IMHO
- `scopes`: by default, only `read`. I need `read,write` in my app, I'm glad to be able to override it
- `expiration`: 1 …

Fixes Trello ResourceOwner

---

DependencyInjection/Configuration.php
OAuth/ResourceOwner/WunderlistResourceOwner.php
Resources/config/oauth.xml
Resources/doc/2-configuring_resource_owners.md
Resources/doc/resource_owners/wunderlist.md
Tests/OAuth/ResourceOwner/WunderlistResourceOwnerTest.php
composer.json

Hi there,
This is WunderlistResourceOwner. I needed to create it as Wunderlist `infos_url` awaits in headers `X-Client-ID` and `X-Access-Token` which is not OAuth2 standard, and couldn't go with a regular generic OAuth2 resource owner.
Doc and test are also provided.
Best

Added WunderlistResourceOwner

---

composer.json

The package `fabpot/php-cs-fixer` requires `symfony/stopwatch` 2.5 or higher.

Fixed Symfony 2.3 tests

---

DependencyInjection/Configuration.php
OAuth/ResourceOwner/AsanaResourceOwner.php
Resources/config/oauth.xml
Resources/doc/2-configuring_resource_owners.md
Resources/doc/resource_owners/asana.md
Tests/OAuth/ResourceOwner/AsanaResourceOwnerTest.php
composer.json

Hi there,
Last of my 3rd PR, a new ResourceOwner, Asana!
Asana follows perfectly OAuth2, and all could be done using just generic oauth2 provider configuration in config file. But Asana creds needs to be refreshed quite often, and using a generic oauth2 provider in my project, I did not find a nice way to use the built-in refresh method of `GenericOAuth2ResourceOwner`. That's why I'm submitting Asana today, to be able to nicely refresh my expired token.
Thanks

Adds Asana ResourceOwner

---

Security/Http/EntryPoint/OAuthEntryPoint.php

Added line to copy query parameters from incoming request to new request on forward only
#1084

Request Parameters are not copied into new Request on forward

---

Form/FOSUBRegistrationFormHandler.php
Tests/Form/FOSUBRegistrationFormHandlerTest.php

This commit caused a BC break - https://github.com/hwi/HWIOAuthBundle/commit/78322998a5400ea00f03f148f38e3a052e97f84a#diff-da386dfe4045fc61ae795f4546b9a247
This fix makes the registration form prepopulated with the user data obtained byh OAuth again.

Prepopulation of registration form doesn't require POST again

---

composer.json

Tests are not needed to be included for production usage.

Exclude tests from Composer autoloader

---

OAuth/ResourceOwner/StackExchangeResourceOwner.php
Tests/OAuth/ResourceOwner/StackExchangeResourceOwnerTest.php

fix #1119
* zlib now required if using stackexchange resource owner
* response is systematically ungzipped (see: https://api.stackexchange.com/docs/compression)
* disabled bearer authentication as it is not supported anymore by SE
* site parameter given (by default stackoverflow)
* application key parameter given (mandatory, see https://stackapps.com/apps/oauth/)
* path for each user item is now good
* fixed tests accordignly
Default configuration (parameters = mandatory fields):
```yaml
stack:
type: stack_exchange
client_id: %stack_client_id%
client_secret: %stack_secret%
options:
key: %stack_key%
site: stackoverflow
```
Result:

fix #1119 - StackExchange Resource Owner

---

Controller/ConnectController.php

Hard to debug what is going on otherwise. Not really sure what the "fix this" comment is refering to in the line above.

When throwing a generic exception at least include the previous exception

---

Controller/ConnectController.php
Tests/Controller/ConnectControllerRedirectToServiceActionTest.php

Resolves issue: https://github.com/hwi/HWIOAuthBundle/issues/837
I wonder if we should be more precise, and instead of catching all RuntimeExceptions thrown, create a new UnknownResourceOwner exception for this specific problem.
Your call.

Throw NotFoundHttpException when unknown resource owner is requested

---

OAuth/ResourceOwner/OdnoklassnikiResourceOwner.php

Domain odnoklassniki.ru is deprecated
Correct domain is ok.ru using HTTPS

Change URLs for Odnoklassniki

---

Controller/ConnectController.php

This fixes https://github.com/hwi/HWIOAuthBundle/issues/430 so that users can refresh the registration page without getting an error message. The downside is that because the key is a timestamp, the total time till completion is now 300 seconds - see https://github.com/hwi/HWIOAuthBundle/blob/master/Controller/ConnectController.php#L104. If we want to extend this period every time they submit the form I can add an additional expiration time.

Do not reset the registration key on each view so that reload works

---

OAuth/ResourceOwner/AbstractResourceOwner.php

Fix #1125
There was an old fix ( #527 ) breaking the behavior with array as parameters by specifying a wrong content-length. **It breaks the Sensiolabs connect adapter** (and maybe others).
Actually Buzz Curl adapter automatically calculate the content-length. So I guess the issue was present with _something else_. That's why I keep backward compatibility with string content variable but IMO it may be also remove.
This is an alternate fix but #657 also works.
There is no test because what needs to be test is the curl request and this imply to add functional test with `nc` (because curl uses an obscure `resource` untestable before sending request to server).
Related to:
* #527 : breaking change
* #657 : fix you didn't merge
* https://github.com/afsy/website/pull/85 : open source project …

Fix #1125 wrong content length calculation for arrays parameters in oauth requests

---

DependencyInjection/Configuration.php
Tests/DependencyInjection/HWIOAuthExtensionTest.php

At the moment, `paths` must be configured for `oauth1`/`oauth2` resource owners even when a `class` is supplied and the paths are defined within this class. After applying this patch, resource owners with `class` can be configured the same way as other pre-defined types.

Use paths from resource owner class

---

Resources/doc/resource_owners/foursquare.md

As I updated the [JcrollFoursquareApiBundle to automatically integrate with the HWIOAuthBundle](https://github.com/jcroll/foursquare-api-bundle#basic-configuration) I thought it would be useful to mention it in your docs.

[RFC] Add mention of "JcrollFoursquareApiBundle" in Foursquare docs

---

Controller/ConnectController.php
Tests/Controller/AbstractConnectControllerTest.php
Tests/Controller/ConnectControllerConnectActionTest.php
Tests/Controller/ConnectControllerConnectServiceActionTest.php
Tests/Controller/ConnectControllerRedirectToServiceActionTest.php
Tests/Controller/ConnectControllerRegistrationActionTest.php

For invalid resource owner throw "not found" exception instead of runtime

---

DependencyInjection/HWIOAuthExtension.php
OAuth/ResourceOwner/StackExchangeResourceOwner.php

The Stack Exchange API [relies](https://api.stackexchange.com/docs/compression) on a HTTP client which is able to handle compressed (GZIP or DEFLATE) responses. After enabling automatic decoding in our cURL instance, the manual decoding is no longer needed.
After applying this patch, all tests should pass with HHVM.

Use automatic HTTP content decoding

---

OAuth/Exception/HttpTransportException.php

We have this problem: requests to oauth providers that fail, or timeout (see issue [655](https://github.com/hwi/HWIOAuthBundle/issues/655)) are thrown as **HttpTransportException** , which end up as uncaught exceptions.
This is a problem, because there's no way to retry the authentication, without messing up the generic error handling for our own, actual server exceptions (internal server error and such).
By extending from **Symfony\Component\Security\Core\Exception\AuthenticationException**,  those transport errors, when dealing with the oauth provider, are treated as authentication errors.
This allows, when a security **failure_path** is defined, to setup an specific authentication error, with a retry option if desired, instead of being redirected to a generic error page.
I'd like to …

Extend HttpTransportException from AuthenticationException

---

.travis.yml

FOSUserBundle 2.0 is now final.

Removed FOSUserBundle dev dependency from travis

---

Security/OAuthUtils.php

Hi,
we have the scenario where we dynamically generate private keys which we can't store in a file. Unfortunately this doesn't let us use the `RSA-SHA1` request signing as it expects to load the private key from file.
With this PR the private key can directly be passed as `$clientSecret` as an alternative I can also adjust the solution to pass in a `Resource` instead of a string?

Allow: private key usage without file

---

DependencyInjection/HWIOAuthExtension.php

[Definition](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Definition.php#L52) takes arguments as an array.

Fix #1240 - Missing array on Definition instanciation

---

OAuth/ResourceOwner/SensioConnectResourceOwner.php

It appear that sensio force the usage of the form data header. This
header is not automatically provided when you use an http client from
httplug, that's the reason why we need to specify it.
Without this fix, the SensioResourceOwner is not working as expected.

Fix sensio resource owner

---

CHANGELOG.md
DependencyInjection/Configuration.php
DependencyInjection/HWIOAuthExtension.php
Resources/config/http_client.xml
Resources/doc/1-setting_up_the_bundle.md
Resources/doc/internals/configuring_the_http_client.md
Resources/doc/internals/reference_configuration.md
Resources/doc/resource_owners/fiware.md
Tests/DependencyInjection/HWIOAuthExtensionTest.php
composer.json

HttplugBundle integration

---

.travis.yml
CHANGELOG.md
Controller/ConnectController.php
DependencyInjection/Configuration.php
DependencyInjection/HWIOAuthExtension.php
Resources/views/Connect/connect_confirm.html.twig
Resources/views/Connect/connect_success.html.twig
Resources/views/Connect/login.html.twig
Resources/views/Connect/registration.html.twig
Resources/views/Connect/registration_success.html.twig
Tests/Controller/AbstractConnectControllerTest.php
Tests/Controller/ConnectControllerConnectActionTest.php
Tests/Controller/ConnectControllerConnectServiceActionTest.php
Tests/Controller/ConnectControllerRegistrationActionTest.php
Tests/DependencyInjection/HWIOAuthExtensionTest.php

Replace deprecated Twig namespaced template paths with correct approach.
Removed support for different template engine than Twig.
Closes #1260, #1278

Improvements for Twig template support

---

DependencyInjection/CompilerPass/SetResourceOwnerServiceNameCompilerPass.php
Form/FOSUBRegistrationFormHandler.php
OAuth/ResourceOwner/GenericOAuth1ResourceOwner.php
OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php
Security/Core/User/OAuthUserProvider.php
Security/OAuthUtils.php

Add the `Content-Type: application/x-www-form-urlencoded` header to all OAuth2 calls made via the GenericOAuth2ResourceOwner class. 
The need for this change was initially caused by errors when using the GoogleResourceOwner. Authentication attempts failed with the following error:
```
[2017-09-19 11:40:29] security.INFO: Authentication request failed. {"exception":"[object] (HWI\\Bundle\\OAuthBundle\\OAuth\\Exception\\HttpTransportException(code: 400): Error while sending HTTP request at {%project_path%}/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/AbstractResourceOwner.php:266, 
Http\\Client\\Exception\\HttpException(code: 400): Client error: `POST https://accounts.google.com/o/oauth2/token` resulted in a `400 Bad Request` response:\n{\n  \"error\" : \"invalid_request\",\n …
```

Add Content-Type header to OAuth2 calls.

---

Resources/doc/1-setting_up_the_bundle.md
Resources/doc/internals/configuring_the_http_client.md

The documentation explain how to migrate to HTTplug with ease.
As you can see, the configuration is not very different than the old way and allow more flexibility.
The only difference is the configuration location, with HttplugBundle of not.

HTTP old config explanations

---

OAuth/ResourceOwnerInterface.php
Security/Core/Authentication/Provider/OAuthProvider.php
Tests/DependencyInjection/HWIOAuthExtensionTest.php
Tests/Security/Core/Authentication/Provider/OAuthProviderTest.php

getRawToken method being called from wrong token object.
Sets created at timestamp as isExpired method was always returning false.

Fixes wrong variable and sets created at timestamp

---

DependencyInjection/Configuration.php

We recently run into the problem to have just one firewall configured in our project and using xml as format for consistency.
To avoid running into the string vs. array problem if just one element available in xml we had to add the fixXmlConfig for the firewall_names property.

Add fixXmlConfig for firewall names

---

OAuth/ResourceOwner/RedditResourceOwner.php

According to Reddit OAuth2 documentation (https://github.com/reddit/reddit/wiki/OAuth2#retrieving-the-access-token) when retrieving the access token the parameters should be sent in the POST data like the following:
`grant_type=authorization_code&code=CODE&redirect_uri=URI`
So, the parameters should be encoded first using `http_build_query`.
Currently, retrieving the access token ends in `unsupported_grant_type`.
This PR fixes the current behaviour.

Fix building of POST data in RedditResourceOwner

---

DependencyInjection/Security/Factory/OAuthFactory.php

Due to #1290, the `$definitionClassname` is not set at `OAuthFactory::createEntryPoint` (line 155).
This PR fix this, by setting the `$definitionClassname` variable.

fix undefined variable $definitionClassname

---

OAuth/ResourceOwner/FiwareResourceOwner.php
OAuth/ResourceOwner/GitHubResourceOwner.php
OAuth/ResourceOwner/JawboneResourceOwner.php
OAuth/ResourceOwner/RunKeeperResourceOwner.php
OAuth/ResourceOwner/ToshlResourceOwner.php
OAuth/ResourceOwner/TraktResourceOwner.php

Authorization headers were passed in a wrong way in several resource owners which are listed below. They should be passed as key => value arrays where the key is the header name.
It caused malfunctions, i.e. in GitHub resource owner the user's e-mail was null, because API request to `https://api.github.com/user/emails` was returning 401 status code (Authorization header wasn't being applied). Example of resulting headers array in httpRequest before the change:
```
Array
(
[0] => Authorization: Bearer 47bce5c74f589f4867dbd57e9ca9f808
[Content-Type] => application/x-www-form-urlencoded
)
```
Resource owners affected by this:
- Fiware
- GitHub
- Jawbone
- RunKeeper
- Toshl
- Trakt

Fixed headers passed to httpRequest method in various resource owners

---

Tests/DependencyInjection/HWIOAuthExtensionTest.php
Tests/Form/FOSUBRegistrationFormHandlerTest.php
Tests/OAuth/ResourceOwner/ResourceOwnerTestCase.php
Tests/OAuth/Response/PathUserResponseTest.php
Tests/Security/Core/Authentication/Provider/OAuthProviderTest.php
Tests/Security/Core/Authentication/Token/OAuthTokenTest.php
Tests/Security/Core/User/EntityUserProviderTest.php
Tests/Security/Core/User/FOSUBUserProviderTest.php
Tests/Security/Core/User/OAuthUserProviderTest.php
Tests/Security/Core/User/OAuthUserTest.php
Tests/Security/OAuthUtilsTest.php

I use the `PHPUnit\Framework\TestCase` notation instead os `PHPUnit_Framework_TestCase` while extending our TestCases. This will help us migrate to `PHPUnit 6`, that <b>now are namespaced</b>, and no longer use snake case class names.

Use PHPUnit\Framework\TestCase instead of PHPUnit_Framework_TestCase

---

OAuth/ResourceOwner/DropboxResourceOwner.php
Tests/OAuth/ResourceOwner/DropboxResourceOwnerTest.php

Implemented getUserInformation method to comply with changes in Dropbox API V2.
see https://www.dropbox.com/developers/reference/migration-guide
For the same reason I have updated identifier mapping to 'account_id' and realname to email since real_name is gone in V2 (is now display_name but nested in a name sub-array within response, and in order to not overcomplicate thing I think it's fine to display email)

Implemented getUserInformation for Dropbox v2

---

Controller/ConnectController.php

Previously the `connectServiceAction` would call `$resourceOwner->getUserInformation()` twice, if it returns early by returning `this.getConfirmationResponse()`:
* here: https://github.com/hwi/HWIOAuthBundle/blob/master/Controller/ConnectController.php#L227
* and here: https://github.com/hwi/HWIOAuthBundle/blob/master/Controller/ConnectController.php#L444
This seems unnecessary. But in the case of Twitter, I also had the problem that the first call to `getUserInformation` would return the expected data, the second would return a response just with an error message in the data.

Fix double call of getUserInformation()

---

Security/Core/Exception/AccountNotLinkedException.php
Tests/Security/Core/Authentication/Token/OAuthTokenTest.php

The embedded token is serialized twice, which makes the unserialization
fail.

Fix serialization of AccountNotLinkedException

---

DependencyInjection/Configuration.php

I get:
```
PHP Fatal error:  Uncaught InvalidArgumentException: Unknown grant role set ""IS_AUTHENTICATED_FULLY"" but it should pass.
```
This is a fix for that.
I've tested with values IS_AUTHENTICATED_FULLY (passes), IS_AUTHENTICATED_REMEMBERED (passes) and IS_AUTHENTICATED_FULLYZ (fails).

Check for grant_rule value IS_AUTHENTICATED_FULLY

---

Tests/Controller/ConnectControllerRegistrationActionTest.php

Fixes the failing controller test on php71 and symfony4

Fix: controller tests for php71

---

OAuth/ResourceOwner/LinkedinResourceOwner.php

Hi,
The LinkedIn Oauth 1 has a security flow.
It does not required an email validation a LinkedIn side.
My website has been hacked by this way with the current implementation of hwi :
- I had an admin account (lets say admin@mysite.com) register on my website with common register form
- The admin@mysite.com account on linkedin did not exist
- The attacker registered at linkedin with admin@mysite.com
- He asked phone verification instead of eamil verification, the account was confirmed
- He did login on my website with linkedin connect and got admin privileges.
These holes can be corrected just by changing the authorization url.
(Linked warned not to use the v1 version anymore).

Changing Linkedin authorization and access token to v2

---

OAuth/ResourceOwner/SlackResourceOwner.php

`Used https://api.slack.com/methods/users.identity` instead of `https://api.slack.com/methods/auth.test` as recommended here : `https://api.slack.com/docs/sign-in-with-slack#identify_users_and_their_workspaces`

Updated slack resource owner to use new Slack API methods

---

OAuth/ResourceOwner/AbstractResourceOwner.php

Fix for "Content-Length" header parameter which must be a string.
It fixes bug with Nyholm/psr7 0.3.0 which try to make a trim on integer at /vendor/nyholm/psr7/src/MessageTrait.php:215

Fix for "Content-Length" header parameter which must be a string

---

OAuth/ResourceOwner/GitLabResourceOwner.php

GitLab API v3 was removed with GitLab 11.0.
https://docs.gitlab.com/ee/api/#current-status
The endpoint `https://gitlab.com/api/v3/user` only returns an error `API V3 is no longer supported. Use API V4 instead.` and no more user data

GitLab: change user endpoint to v4

---

DependencyInjection/Security/Factory/OAuthFactory.php

\HWI\Bundle\OAuthBundle\Controller\ConnectController::getResourceOwnerByName 
have to get services for > SF 4.0

[SF 4.0][BUG] set hwi_oauth.resource_ownermap.* services public

---

Resources/doc/internals/configuring_the_http_client.md

verify_peer parameter has been renamed into verify
http://php-translation.readthedocs.io/en/latest/guides/configure-httplug.html

Update to httplug configuration

---

OAuth/ResourceOwner/FacebookResourceOwner.php

Hey,
following this issue https://github.com/hwi/HWIOAuthBundle/issues/1431;
I have tested the Facebook API v3.1 and it seems to not have some breaking change for Facebook Connect and GET me. 
Feel free to comment and ask me any modification!
Cheers

Update Facebook endpoint to v3.1

---

OAuth/ResourceOwner/YahooResourceOwner.php

Somehow this was not caught by the test suite.
```php
protected function httpRequest($url, $content = null, array $headers = array(), $method = null, array $parameters = array())
```

YahooResourceOwner > Fix inconsistency in arguments

---

OAuth/ResourceOwner/SensioConnectResourceOwner.php
Resources/doc/2-configuring_resource_owners.md
Resources/doc/resource_owners/sensio_connect.md

At this moment, the SSL cert on the old URLs is broken. So, until now, this change wasn't strictly needed (the old URLs still worked), but at this moment it is. But I don't believe there is any difference in behavior - we just made this change manually for SymfonyCasts by overriding this config.
We could go further in the future and change the config keys, class names, etc. But in this PR, I strictly wanted to get things working.

Updating SensioConnect to use the new URLs

---

OAuth/ResourceOwner/KeycloakResourceOwner.php
Tests/OAuth/ResourceOwner/KeycloakResourceOwnerTest.php

Hello guys, we created a new authentication provider integration for [keycloak](https://www.keycloak.org/) which is an open source identity and access management system. 
We actually need also to integrate this provider in 0.5 version for our purposes.  How should we proceed about it? Can you provide a backport or should we open another PR for 0.5 version?
Thanks a lot

Keycloak Provider

---

OAuth/ResourceOwner/LinkedinResourceOwner.php
OAuth/Response/LinkedinUserResponse.php
Resources/doc/resource_owners/linkedin.md
Tests/OAuth/ResourceOwner/LinkedinResourceOwnerTest.php

Linkedin has depreciate its v1 API; it will stop working on the 1st March
2019 (https://engineering.linkedin.com/blog/2018/12/developer-program-updates).
The change to the v2 was done for the authorization & access_token
endpoints in 8951d956baf1 but the endpoint to fetch the info was still v1.
The v2 endpoint return a very different payload; there is a lot less info
with the default permission and there isn't the email address anymore.
Therefore an extra request is done to get the user's email address and a
custom UserResponse has been written to support the complex JSON schema.
Note: I get some inspiration from https://github.com/laravel/socialite/pull/310/files

Use Linkedin API v2 to fetch user info

---

Resources/config/oauth.xml
Resources/config/twig.xml

Since Symfony 3.4, services are private by default, so we can remove the `public="false"` tags.
Note, I did not touch the public services.

Services are private by default since Symfony 3.4

---

Controller/ConnectController.php
README.md

[BC Proposal] I want to replace old Symfony Controller with AbstractController. I remove support with php5.6 and Symfony ^2.8 to make it possible.
What do you think?
Made with :heart: by [![Open Source Saturday](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg)](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/)

Move to abstract controller

---

CHANGELOG.md
Resources/config/oauth.xml
Resources/config/templating.xml
Resources/config/twig.xml

The use of service class parameters is discouraged by Symfony, let's remove some.
Note, the resource owner class parameters cannot be removed as they are used to create the resource services in `HWIOAuthExtension`.

Remove unnecessary class parameters

---

Resources/doc/resource_owners/others.md

While testing #1514, I discovered that the doc example for a generic resource owner is broken, because the `class` option is no longer optional.
This fixes the docs example.

Fix generic resource owner example

---

OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php

This PR fixes #1513: the token request for the generic OAuth2 resource owner was sending the client secret in the body, which is not preferred and discouraged by the RFC.

Allow to use authentication in "get token requests" to match OAuth2 RFC

---

DependencyInjection/HWIOAuthExtension.php
DependencyInjection/Security/Factory/OAuthFactory.php

We can safely remove `DefinitionDecorator` as the upcoming 1.0 release focuses on Symfony 3.4|4.2

Remove DefinitionDecorator check

---

Tests/Security/Core/Authentication/Token/OAuthTokenTest.php

I've change the failing serialization test based on https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Tests/Exception/CustomUserMessageAuthenticationExceptionTest.php#L58

Fix serialization token test

---

Tests/Security/Core/Authentication/Provider/OAuthProviderTest.php

First attempt to get rid of the TokenInterface::getRoles deprecation notice in Symfony 4.3

Fix TokenInterface::getRoles deprecation notice

---

Controller/ConnectController.php
Resources/config/controller.xml

Trying to remove deprecation:
```
Auto-injection of the container for "HWI\Bundle\OAuthBundle\Controller\ConnectController" is deprecated since Symfony 4.2. Configure it as a service instead.
```

Replace usage of `AbstractController` with proper traits usage

---

Security/Core/Exception/AccountNotLinkedException.php
Tests/Security/Core/Authentication/Token/OAuthTokenTest.php

This is an attempt of removing the `__serialize` method deprecation for Symfony 4.3, not sure if it's the way...

Fix AccountNotLinkedException::__serialize deprecation notice

---

Security/Core/User/EntityUserProvider.php
Security/Core/User/FOSUBUserProvider.php
Tests/Fixtures/FOSUser.php
Tests/Security/Core/User/EntityUserProviderTest.php
Tests/Security/Core/User/FOSUBUserProviderTest.php

The bundle doesn't fill the property `username` when code throwing the `Symfony\Component\Security\Core\Exception\UsernameNotFoundException`.

Fill username when throwing UsernameNotFoundException

---

OAuth/ResourceOwner/TwitchResourceOwner.php

The resource owner of twitch was no longer working. 
I got a 400 error on the response of the access_token.
The correction allows to use natively the doGetTokenRequest method of GenericOAuth2ResourceOwner class which uses the client_id and the client_secret.

Fix : Twitch Resource Owner

---

Tests/App/AppKernel.php
Tests/App/config.yml
Tests/Fixtures/CustomOAuthToken.php
Tests/Fixtures/FOSUser.php
Tests/Functional/Controller/ConnectControllerTest.php
Tests/Security/Core/User/FOSUBUserProviderTest.php
composer.json

I added a couple of functional test for `ConnectController` to check that https://github.com/hwi/HWIOAuthBundle/pull/1537 works fine. Using FOSUserBundle has added some deprecations.

Add functional test for ConnectController

---

Tests/Controller/AbstractConnectControllerTest.php
Tests/Controller/LoginControllerTest.php
Tests/Controller/RedirectToServiceControllerTest.php

It fixes the wrong usage of Symfony TestCase, this TestCase was part of the internal Symfony test suite. It has been
removed with .gitattribute and is no more part of the Sf package. This
commit uses the standard PHPUnit TestCase instead.
It is part of the #SymfonyHackday .

Make the testsuite green again

---

Controller/ConnectController.php
Tests/App/config.yml
Tests/Controller/ConnectControllerConnectServiceActionTest.php
Tests/Controller/ConnectControllerRegistrationActionTest.php
Tests/Fixtures/FOSUser.php
Tests/Fixtures/User.php

Add roles in tests users
Symfony changed in 4.4 and now does not authorize users without roles. (and it's weird it was ok before)
#SymfonyHackday
-----------------------------------------------------
Sorry the testsuite can't be green because we're dependent to FOSUser [which triggers deprecation notices](https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2942#issuecomment-557803851). And btw I'm not sure it's a great idea to test such integration.

Tend to green tests

---

Security/Core/Exception/AccountNotLinkedException.php
Tests/Security/Core/Authentication/Token/OAuthTokenTest.php

Now check if exist method of UsernameNotFoundException and is not necessary use of AuthenticationException.
And change test to check method __serialize instead of serialize.

UsernameNotFoundException refix

---

Controller/LoginController.php
Tests/Controller/LoginControllerTest.php

While testing the master branch on one of my applications I noticed this issue on the login route:
The provided patch fixed this issue.

fix issue when there is no authentication token available

---

.travis.yml
Makefile
Security/Core/Authentication/Token/OAuthToken.php
Tests/Functional/Controller/ConnectControllerTest.php
Tests/Functional/Controller/LoginControllerTest.php
composer.json
phpunit.xml.dist

This makes travis green again.
- for now we are not making the build fail on direct deprecations anymore. Will check within the next days if I can get rid of them completely.
- this also includes the php 7.4 serialization fix similar as in https://github.com/hwi/HWIOAuthBundle/pull/1580. @mathieudz can you have a look if this makes sense to you? I fixed it so it works with php < 7.4 and 7.4 on Symfony < 4.3 and >= 4.3.

fix travis build

---

Controller/LoginController.php
Resources/config/controller.xml
Tests/Controller/LoginControllerTest.php

Currently the `symfony/twig-bundle` is only a development requirement of this bundle. Though, because the Twig `Environment` is injected into the `LoginController` has become requirement and compiling the Symfony service container in an application fails when Twig is not installed.
This is currently the case for our application, which isn't using the `LoginController`.
This PR changes the Twig requirement back to an optional requirement of the bundle by the using Symfony's `AbstractController` (and it's service subscribing).

Optional Twig dependency for LoginController

---

OAuth/ResourceOwner/Auth0ResourceOwner.php
Tests/OAuth/ResourceOwner/Auth0ResourceOwnerTest.php
Tests/OAuth/ResourceOwner/ResourceOwnerTestCase.php

I noticed that the actual bug of the client ID and client secret not being sent was already fixed in #1594. Thanks for that! 😄 
With creating a temporary work-around for this issue, I created a fix involving less code overloading in the `Auth0ResourceOwner` class. Possibly reducing future regressions when changing the `GenericOAuth2ResourceOwner`.
I've also added tests to assert the requests that would be sent to Auth0.

Improvements for Auth0ResourceOwner to reduce regression in the future

---

Tests/OAuth/ResourceOwner/Auth0ResourceOwnerTest.php

This PR improves the assertion descriptions added in #1604 to be relevant for both the `testGetAccessTokenSendsExpectedRequest` and `testGetUserInformationSendsExpectedRequest` test.

Improve assertion descriptions in Auth0ResourceOwnerTest::mockHttpClientSendRequestWithRequestAssertions to be relevant for both request tests

---

Resources/config/controller.xml

This PR adds the `setContainer` call to service container configuration for `LoginController`.
As mentioned in https://github.com/hwi/HWIOAuthBundle/pull/1611#discussion_r384959036, I tested adding the `container.service_subscriber` tag.
This creates a service locator with the subscribed services of the `LoginController` (`AbstractController`), but the `setContainer` call isn't added with service locator by any other compiler pass than the `AutowirePass`. As the service locator is created with a hashed service id, you're not really able to reference it manually.

Add missing setContainer call to service container configuration for LoginController

---

OAuth/ResourceOwner/AzureResourceOwner.php
Resources/doc/resource_owners/azure.md
Tests/OAuth/ResourceOwner/AzureResourceOwnerTest.php

This will fix azure `authorization_url` and `access_token_url` and remove the `resource` parameter (could not find any ref in the current azure ad docs of this parameter).
I am currently using this fix to authenticate users from Azure AD. The URLs in this fix can be found [in the aure AD documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols).

Fix azure urls

---

OAuth/ResourceOwner/AzureResourceOwner.php
Tests/OAuth/ResourceOwner/AzureResourceOwnerTest.php

I just added possibility to get FirstName & LastName from UserResponseInterface.
Data already exists (`realname` is a concat of `given_name` and `family_name`)

Add first_name & last_name in AzureResourceOwner

---

OAuth/ResourceOwner/Auth0ResourceOwner.php

This simple patch has the Auth0 Resource Owner use the value in 'sub' for the user identifier.  Auth0 does not use 'user_id'.

Auth0 sends user identifier in 'sub', not 'user_id'

---

OAuth/RequestDataStorage/SessionStorage.php
OAuth/RequestDataStorageInterface.php
OAuth/ResourceOwner/AbstractResourceOwner.php
OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php
OAuth/ResourceOwnerInterface.php
OAuth/State/State.php
OAuth/StateInterface.php
Security/Http/ResourceOwnerMap.php
Security/OAuthUtils.php
Tests/Fixtures/MyCustomProvider.php
Tests/OAuth/RequestDataStorage/SessionStorageTest.php
Tests/OAuth/ResourceOwner/AppleResourceOwnerTest.php
Tests/OAuth/ResourceOwner/DailymotionResourceOwnerTest.php
Tests/OAuth/ResourceOwner/DropboxResourceOwnerTest.php
Tests/OAuth/ResourceOwner/FacebookResourceOwnerTest.php
Tests/OAuth/ResourceOwner/GenericOAuth2ResourceOwnerTest.php
Tests/OAuth/ResourceOwner/GoogleResourceOwnerTest.php
Tests/OAuth/ResourceOwner/HubicResourceOwnerTest.php
Tests/OAuth/ResourceOwner/ResourceOwnerTestCase.php
Tests/OAuth/ResourceOwner/YoutubeResourceOwnerTest.php
Tests/OAuth/State/StateTest.php

I've made a number of fixes to the state parameter support, the most important being the persistence after receiving the state parameters back from the OAuth2 resource owner.
I've also added tests for the `SessionStorage` with this opportunity.

Extended state parameter support to be persistent when returned from the resource owner

---

OAuth/ResourceOwner/FacebookResourceOwner.php

No differences in API spotted, login feature working as on 3.1, same user data is returned, fixes https://github.com/hwi/HWIOAuthBundle/issues/1659

Upgrade Facebook API version to 8.0

---

OAuth/ResourceOwner/TwitchResourceOwner.php

Twitch API [now requires the following HTTP headers](https://dev.twitch.tv/docs/api):
- a proper `Authorization` header
- a new `Client-ID` header 
User information paths [have also changed](https://dev.twitch.tv/docs/api/reference#get-users).
This PR updates the TwitchResourceOwner to follow these API changes and thus fixes #1669

Updated Twitch resource owner to follow latest Twitch API.

---

OAuth/ResourceOwner/AzureResourceOwner.php

Quick solution for issue #1629 with compatibility for both "id_token" and "access_token".
Reference:
- https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens
- https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

Use "access_token" instead of "id_token" in Azure

---

Resources/doc/2-configuring_resource_owners.md
Resources/doc/3-configuring_the_security_layer.md
Resources/doc/bonus/facebook-connect.md
Resources/doc/internals/reference_configuration.md
Resources/doc/internals/response_object_and_paths.md
Tests/App/config.yml
Tests/App/security.php
Tests/DependencyInjection/HWIOAuthExtensionTest.php

This should reduce confusion between our docs & Symfony Flex receipt - refs: https://github.com/hwi/HWIOAuthBundle/issues/1677#issuecomment-753490294

Change default security firewall name to same as in Flex receipt

---

Resources/doc/1-setting_up_the_bundle.md
Resources/doc/2-configuring_resource_owners.md

Explain how to install the bundle with recent versions of Symfony and switch to HttpClient instead of Guzzle.
Currently, there is a problem caused by Flex. See https://github.com/symfony/flex/issues/751.

docs: use HttpClient and Symfony Flex

---

OAuth/ResourceOwner/GitHubResourceOwner.php

Closes https://github.com/hwi/HWIOAuthBundle/issues/1650
See https://developer.github.com/changes/2020-02-14-deprecating-oauth-app-endpoint/ for the announcement and https://docs.github.com/en/rest/reference/apps#delete-an-app-token for the doc of the new endpoint.

Migrate to the new github revocation endpoint

---

OAuth/ResourceOwner/AppleResourceOwner.php

I got the error : 
> E_NOTICE: Undefined index: name
on line 94
Probably caused by my configuration that says : 
>             scope:          "email"
Instead of what is in the documentation : 
>            scope:          "name email"
With this it should work with both configurations.

Fixes notice in AppleResourceOwner.php

---

Security/Core/User/OAuthUser.php
Tests/Fixtures/User.php
phpunit.xml.dist

This removes 2 deprecations related to:
```
Class "HWI\Bundle\OAuthBundle\Tests\Fixtures\User" should implement method "Symfony\Component\Security\Core\User\UserInterface::getUserIdentifier()": returns the identifier for this user (e.g. its username or e-mailaddress)
```
And marks the 4 as "acceptable" cause those are not an easy fix.

Added further compatibility with Symfony Security 5.3+

---

.github/workflows/ci.yaml
composer.json

PHP 7.2 is End of Life (EOL) for a long time so I think it's time to drop support for it.

Drop PHP 7.2

---

Controller/ConnectController.php

Accepting the response from the event listener associated with HWIOAuthEvents::CONNECT_COMPLETED whenever it's set instead of always using the @HWIOAuth/Connect/connect_success.html.twig template rendering
No worries about what will be the response because it'll be cast by the setResponse() method which will fire an exception in case a bad response format was set

Customizing the CONNECT_COMPLETED response

---

OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php
Tests/OAuth/ResourceOwner/GenericOAuth2ResourceOwnerTest.php

There is no protection when the state parameter is empty, only if it's invalid. Although the function returns "false", there is no check for the return value, only the Exception thrown.
This allows attacker to perform account takeover via no CSRF protection.

Add scenario for missing state

---

Security/Core/Exception/AccountNotLinkedException.php

```
1x: Implementing the "HWI\Bundle\OAuthBundle\Security\Core\Exception\AccountNotLinkedException::serialize()" method is deprecated since Symfony 4.3, implement the __serialize() and __unserialize() methods instead.
1x in ConnectControllerTest::testRegistration from HWI\Bundle\OAuthBundle\Tests\Functional\Controller
1x: Implementing the "HWI\Bundle\OAuthBundle\Security\Core\Exception\AccountNotLinkedException::unserialize()" method is deprecated since Symfony 4.3, implement the __serialize() and __unserialize() methods instead.
1x in ConnectControllerTest::testRegistration from HWI\Bundle\OAuthBundle\Tests\Functional\Controller

Maintain | Remove leftover Symfony 4.3 BC layer

---

Security/Core/User/EntityUserProvider.php
Security/Core/User/FOSUBUserProvider.php
Security/Core/User/OAuthUserProvider.php
Tests/Security/Core/User/EntityUserProviderTest.php
Tests/Security/Core/User/OAuthUserProviderTest.php

This method was added in Symfony 5.3: https://github.com/symfony/symfony/blob/19b96f89a07b290181eeca49d9b98d968865d4c9/src/Symfony/Component/Security/Core/User/UserProviderInterface.php#L32
[As a replacement of `UserProviderInterface::loadUserByUsername`](https://github.com/symfony/symfony/blob/5.4/UPGRADE-5.3.md#security).
In `EntityUserProvider` I was going to call `loadUserByIdentifier` from `loadUserByUsername`, but since `loadUserByIdentifier` should throw the new `UserNotFoundException`, the code was a bit messy, I think this is cleaner.

Implement UserProviderInterface::loadUserByIdentifier

---

DependencyInjection/Security/Factory/OAuthFactory.php
Event/FilterUserResponseEvent.php
Event/FormEvent.php
Event/GetResponseUserEvent.php
Form/FOSUBRegistrationFormHandler.php
OAuth/Exception/HttpTransportException.php
OAuth/Response/LinkedinUserResponse.php
OAuth/Response/SensioConnectUserResponse.php
Security/Core/Authentication/Provider/OAuthProvider.php
Security/Core/Exception/AccountNotLinkedException.php
Security/Core/User/EntityUserProvider.php
Security/Core/User/FOSUBUserProvider.php
Security/Core/User/OAuthUser.php
Security/Core/User/OAuthUserProvider.php
Security/Http/EntryPoint/OAuthEntryPoint.php
Security/Http/Firewall/OAuthListener.php
Security/Http/ResourceOwnerMap.php
Security/OAuthUtils.php
Templating/Helper/OAuthHelper.php

Related to: #1743
To be easier to review I list the ones I left without annotation (I'm not listing the already `final` ones and `abstract`):
- https://github.com/hwi/HWIOAuthBundle/blob/master/Event/UserEvent.php (there are other events extending it).
- https://github.com/hwi/HWIOAuthBundle/blob/master/OAuth/Response/PathUserResponse.php (some extends from this).
- https://github.com/hwi/HWIOAuthBundle/blob/master/Security/Core/Authentication/Token/OAuthToken.php (in tests there is a [CustomOAuthToken](https://github.com/hwi/HWIOAuthBundle/blob/master/Tests/Fixtures/CustomOAuthToken.php) extending)
And [ResourceOwners](https://github.com/hwi/HWIOAuthBundle/tree/master/OAuth/ResourceOwner) that I wasn't sure what to do, maybe they could be marked as internal

Mark classes as final

---

Controller/ConnectController.php
Controller/LoginController.php
Resources/config/controller.xml
Tests/Controller/AbstractConnectControllerTest.php
Tests/Controller/ConnectControllerConnectServiceActionTest.php
Tests/Controller/ConnectControllerRegistrationActionTest.php
Tests/Controller/LoginControllerTest.php

This PR changes:
- removed dependency on `AbstractController` in `LoginController`,
- replaced dependency on parameters in `ConnectController` in favor of injecting them into `__construct()`

Bugfix | Fixed bundle controllers to not depend on container if possible

---

Controller/ConnectController.php

When calling:
https://github.com/hwi/HWIOAuthBundle/blob/e76e83035dfb09f74391897377b4a9ef37f75d88/Controller/ConnectController.php#L309-L312
[`InteractiveLoginEvent` in 4.4 does not implement `Event` from `Contracts`](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Http/Event/InteractiveLoginEvent.php#L14), so dispatch method throws a TypeError.

Fix compatibility with symfony 4.4

---

Tests/Controller/ConnectControllerRegistrationActionTest.php
Tests/Functional/Controller/ConnectControllerTest.php
Tests/Functional/Controller/LoginControllerTest.php
Tests/Functional/IntegrationTest.php

This removes deprecation warning in PHPUnit:
```
PHPUnit\Framework\TestCase::prophesize() is deprecated and will be removed in PHPUnit 10. Please use the trait provided by phpspec/prophecy-phpunit
```

Bugfix | Remove usage of `$this->prophesize()` in favour of mocking & use internal Symfony container

---

.github/workflows/ci.yaml
composer.json

With this, functional tests are executed, it used to failed before #1689, that can be seen in https://github.com/franmomu/HWIOAuthBundle/pull/2, now it should pass.
Replaces https://github.com/hwi/HWIOAuthBundle/pull/1750
This job will be removed in `2.0`, but it is useful to execute our functional tests in CI instead of skipping them.
Needs https://github.com/hwi/HWIOAuthBundle/pull/1752 and https://github.com/hwi/HWIOAuthBundle/pull/1751

Add test to CI using FOSUserBundle

---

DependencyInjection/HWIOAuthExtension.php
Tests/DependencyInjection/HWIOAuthExtensionTest.php

When using the last version (`1.4` is already in packagist 👍 ), this error appears:
```
You have requested a non-existent parameter "hwi_oauth.connect.confirmation".
```
That's because it is used in:
https://github.com/hwi/HWIOAuthBundle/blob/d4986a7280beaccb336535e6abbcf7a85004517c/Resources/config/controller.xml#L16
But it is only defined in:
https://github.com/hwi/HWIOAuthBundle/blob/d4986a7280beaccb336535e6abbcf7a85004517c/DependencyInjection/HWIOAuthExtension.php#L201
The proper way to fix this I guess is to check if `connect` is enabled and then load the `ConnectController`, but that would be BC break since the controller service won't be available.
I tried to make the argument optional, but I couldn't, I'm not sure if that's possible with a parameter from the container.

Define `hwi_oauth.connect.confirmation` parameter

---

DependencyInjection/Security/Factory/OAuthAuthenticatorFactory.php
Security/Http/Authenticator/OAuthAuthenticator.php
Tests/Security/Http/Authenticator/OAuthAuthenticatorTest.php

The success and failure handlers should always be present in the Authenticator. It is resolved by `AbstractFactory:: createAuthenticationSuccessHandler()`:
https://github.com/symfony/symfony/blob/5.1/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/AbstractFactory.php#L165-L174
where default handler is resolved if none is set for the current firewall.
This issue makes it impossible to log in unless someone provides a custom success handler. I discovered this bug after upgrading to 1.4 and switching to new authentication system.

[bug] fix missing success/failure handler

---

DependencyInjection/HWIOAuthExtension.php
Tests/DependencyInjection/HWIOAuthExtensionTest.php

Based on https://github.com/hwi/HWIOAuthBundle/pull/1756#issuecomment-887939798, I didn't realised that there was a new `1.4` branch.
This is a cherry-pick of the commit in `master`.

Define hwi_oauth.connect.confirmation parameter

---

CHANGELOG.md
Resources/config/twig.xml
Security/OAuthUtils.php
Templating/Helper/OAuthHelper.php
Twig/Extension/OAuthExtension.php
Twig/Extension/OAuthRuntime.php
composer.json

This makes the twig extension lazy. See https://symfony.com/doc/current/templating/twig_extension.html#creating-lazy-loaded-twig-extensions
This has the benefit that not all the services are instantiated already when the twig environment is bootstrapped. Since on my app I rarely use the twig functions provided by this bundle this will speed things up for a lot of requests.
Replaces https://github.com/hwi/HWIOAuthBundle/pull/1719 and targets master without the BC layer.

make twig extension lazy by using a Runtime

---

Security/Core/Authentication/Provider/OAuthProvider.php
Tests/Security/Core/Authentication/Provider/OAuthProviderTest.php

Don't re-use creation date from previous token if was already expired  in `OAuthProvider`

---

DependencyInjection/HWIOAuthExtension.php

Bugfix | Prevent issue with missing parameter when `connect` option is not enabled

---

Resources/config/util.xml

The Symfony HTTP client service definition introduced in #1681 was incomplete, and unusable in such state. I copied how it's built from the main framework.
[EDIT] IMHO we should still go forward with #1787, and use the Symfony client as default.

[2.x] Fix HTTP client definition

---

CHANGELOG.md
OAuth/ResourceOwner/VkontakteResourceOwner.php

Bugfix: Fixed `VkontakteResourceOwner` option: `api_version` to not point to deprecated one

---

CHANGELOG.md
Templating/Helper/OAuthHelper.php

I'm targeting this branche because it's BC.
Added function to check if "getMainRequest" exists, otherwise use the current "getMasterRequest":
From Symfony 5.3 notes:
* Deprecate the `RequestStack::getMasterRequest()` method and add `getMainRequest()` as replacement

getMasterRequest is deprecated since Symfony 5.3

---

DependencyInjection/Security/Factory/OAuthFactory.php
Resources/config/oauth.xml
Tests/Controller/ConnectControllerRegistrationActionTest.php
Tests/Security/Core/Authentication/Provider/OAuthProviderTest.php
Tests/Security/Core/User/OAuthUserProviderTest.php
Tests/Security/Http/Authenticator/OAuthAuthenticatorTest.php

Fixes https://github.com/hwi/HWIOAuthBundle/issues/1783
If you could give it a try @garak
There is still a deprecation that we have to break BC or wait for major release.
https://github.com/hwi/HWIOAuthBundle/blob/cd20030f27724524aa39a001eb5b698908a87973/Security/Core/Exception/AccountNotLinkedException.php#L14-L17
`UsernameNotFoundException` is deprecated in favor of `UserNotFoundException`, we could optionally extend from `UserNotFoundException` if the class exists.

Fix Symfony 5.3 remaining deprecations

---

Tests/Security/Core/User/EntityUserProviderTest.php

Currently EntityUserProviderTest is skipped, since ManagerRegistry is an interface instead of a class

Fix EntityUserProviderTest

---

OAuth/ResourceOwner/AbstractResourceOwner.php
Tests/OAuth/ResourceOwner/GenericOAuth1ResourceOwnerTest.php
Tests/OAuth/ResourceOwner/GenericOAuth2ResourceOwnerTest.php

Fixes #1820
Parses text/html;charset=utf-8 response as string instead of json. This is necessary for OAuth1.0a responses from Twitter.

Fix parsing OAuth1.0a responses for Twitter

---

OAuth/ResourceOwner/SpotifyResourceOwner.php
Tests/OAuth/ResourceOwner/SpotifyResourceOwnerTest.php

Updates the SpotifyResourceOwner to be able to retrieve the profile picture of the user from the UserResponse by calling $response->getProfilePicture()

Spotify | Add path for profile picture

---

DependencyInjection/HWIOAuthExtension.php
HWIOAuthBundle.php
OAuth/ResourceOwner/AbstractResourceOwner.php

Performs an HTTP request.
HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\AbstractResourceOwner::httpRequest
If the $content is string, then the $content was lost. $content passed to $this->httpClient->request for array only, not string. 
I was getting an 400 response from the Auth0 server on /oauth/token instead of access token.
This is fixed. Tested on Auth0.

Pass content in HTTP POST request on OAuth server

---

HWIOAuthBundle.php

PHP CS Fixer fails since the use statements are not sorted alphabetically.  
See failing job:
https://github.com/hwi/HWIOAuthBundle/runs/4417396961?check_suite_focus=true

Fix code style issue

---

Resources/doc/resource_owners/google.md

Google Moments API is not available since 2015 (cannot find original Google Blog post, only this one describing that: https://www.igorkromin.net/index.php/2015/06/10/what-to-do-when-the-google-plus-moments-api-is-no-longer-supported/ )

Remove Google Moments API from docs

---

Security/Core/Authentication/Token/AbstractOAuthToken.php
Security/Core/Authentication/Token/OAuthToken.php

Bugfix | Restore wrongly moved `AbstractOAuthToken::getCredentials()`

---

Controller/ConnectController.php
DependencyInjection/HWIOAuthExtension.php
Resources/config/controller.xml
Tests/Controller/AbstractConnectControllerTest.php
Tests/Controller/RedirectToServiceControllerTest.php
Tests/DependencyInjection/HWIOAuthExtensionTest.php

Bugfix | Fixed issue when `connect` configuration is not set but `ConnectController` was used

---

Security/Core/Authentication/Token/AbstractOAuthToken.php
Security/Http/Authenticator/OAuthAuthenticator.php
Security/Http/Authenticator/Passport/SelfValidatedOAuthPassport.php
Tests/Fixtures/CustomOAuthToken.php
Tests/Security/Http/Authenticator/OAuthAuthenticatorTest.php

With the new authentication manager the access token could not be refreshed by a request listener without copying part of the code from the OAuthAuthenticator. I had reviewed authenticator and:
1. made a public method refreshToken. Using DI I can now pass authenticator in every function/listener, get new token and replace them in token storage.
2. Because we already have in `authenticate()` function a ready to use `OAuthToken`, I have extended SelfValidatedPassport and pass token to them instead of a UserBadge.
3. It is also possible to implement a kind of RememberMe function but with an `OAuthRememberMeToken`. You can store resource owner name and refresh_token with unlimited lifetime (usually you can get it with scope `offline`) in the db and get a new access token every time without …

Reviewed authenticator and made refreshToken method public.

---

src/Security/Core/Authentication/Provider/OAuthProvider.php
tests/Security/Core/Authentication/Provider/OAuthProviderTest.php

Like in OAuthAuthenticator token of the same class will be created.
fix in tests - i think legacy authenticator will have all 5.4.x versions.

oauth token of the same class will be created. fix in tests

---

src/Security/Core/Authentication/Provider/OAuthProvider.php
tests/Security/Core/Authentication/Provider/OAuthProviderTest.php

It should be possible to refresh access token using only a valid refresh token without infos about owner.
I need it for my "OAuthRememberMeToken". Probably it is needed also for #1825
P.S. I have used it for couple of month in my own OAuthProvirder (I had to replace the default one for this small changes hier and in merged #1849)

Allow null User for refreshing oauth token

---

CHANGELOG.md
src/Controller/ConnectController.php
src/Controller/RedirectToServiceController.php
src/DependencyInjection/CompilerPass/ResourceOwnerMapCompilerPass.php
src/Resources/config/controller.php
src/Security/Http/ResourceOwnerMapLocator.php
tests/Controller/AbstractConnectControllerTest.php
tests/Controller/ConnectControllerConnectServiceActionTest.php
tests/Controller/RedirectToServiceControllerTest.php

Two controllers have this parameter in their constructor, although they can be found in $resourceOwnerMapLocator.
I think rather $resourceOwnerMapLocator is a primary source for this.

Review: Removed/replaced redundant parameter $firewallNames  in Controllers

---

CHANGELOG.md
docs/2-configuring_resource_owners.md
src/DependencyInjection/CompilerPass/RefreshOAuthTokenCompilerPass.php
src/DependencyInjection/Security/Factory/OAuthAuthenticatorFactory.php
src/DependencyInjection/Security/Factory/OAuthFactory.php
src/HWIOAuthBundle.php
src/OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php
src/Resources/config/oauth.php
src/Security/Http/Firewall/AbstractRefreshAccessTokenListener.php
src/Security/Http/Firewall/RefreshAccessTokenListener.php
src/Security/Http/Firewall/RefreshAccessTokenListenerOld.php
tests/App/Controller/HomeController.php
tests/App/config/routing.yaml
tests/App/config/security_v4.yaml
tests/App/config/security_v5.yaml
tests/App/config/security_v5_bc.yaml
tests/App/config/security_v6.yaml
tests/Functional/IntegrationTest.php
tests/Security/Http/RefreshOnExpireTest.php

Please take a look to my implementation of auto-refresh-expired-token functionality.
During creating of Authenticator/Provider will also created a listener that fires after OAuthToken was set from session to token storage. This is the best moment to refresh or invalidate the token, because it fires before the symfony's access control listener.
If the old token could not be refreshed user will be seamless logged out, on a private page the user is redirected to login page.
If PR accepted I will also add listener to symfony 4.4 and write some tests.

auto refresh oauth2 token on expire

---

CHANGELOG.md
src/DependencyInjection/CompilerPass/EnableRefreshOAuthTokenListenerCompilerPass.php
src/DependencyInjection/HWIOAuthExtension.php
src/HWIOAuthBundle.php
src/Security/Http/Firewall/AbstractRefreshAccessTokenListener.php
tests/App/config/config.yaml
tests/App/config/routing.yaml
tests/App/config/security_v4.yaml
tests/App/config/security_v5.yaml
tests/App/config/security_v5_bc.yaml
tests/App/config/security_v6.yaml
tests/Functional/Security/Http/Firewall/RefreshTokenListenerTest.php

If firewall is lazy, then current token is often initialising during `kernel.response`. In this case the listener, that stores auth token from token storage back to the session, will be registered too late and will not be executed. Thus, refresh token action repeats on each request right after the first token has expired.

Bugfix: Refresh token listener should not be lazy.

---

src/DependencyInjection/CompilerPass/ResourceOwnerMapCompilerPass.php
src/DependencyInjection/HWIOAuthExtension.php
src/Resources/config/resource_owners.php
tests/App/ResourceOwner/CustomResourceOwner.php
tests/App/config/config.yaml
tests/App/config/routing.yaml
tests/App/config/security_v4.yaml
tests/App/config/security_v5.yaml
tests/App/config/security_v5_bc.yaml
tests/App/config/security_v6.yaml
tests/DependencyInjection/HWIOAuthExtensionTest.php
tests/Functional/Controller/LoginControllerTest.php

I don't think we need the tag `hwi_oauth.resource_owner`. Registering the service locator ourselves seems straightforward and fixes https://github.com/hwi/HWIOAuthBundle/issues/1873

set resourceOwner services directly without using tag

---

DependencyInjection/Configuration.php

This PR allows to set a false value for use_authorization_to_get_token in the config.
Useful to configure the generic OAuth2 resource owner, as the default value is true.
Previously, setting a false value was considered empty, then unset.

Allow "use_authorization_to_get_token" to be configured to false for generic OAuth2

---

CHANGELOG.md
src/OAuth/ResourceOwner/AbstractResourceOwner.php

Catch also the `TransportExceptionInterface` in `AbstractResourceOwner::getResponseContent()` method

---

CHANGELOG.md
src/DependencyInjection/CompilerPass/ResourceOwnerMapCompilerPass.php
src/Resources/config/oauth.php
src/Security/OAuthUtils.php
tests/App/config/routing.yaml
tests/App/config/security_v4.yaml
tests/App/config/security_v5.yaml
tests/App/config/security_v5_bc.yaml
tests/App/config/security_v6.yaml
tests/App/templates/login.html.twig
tests/Controller/Connect/AbstractConnectControllerTest.php
tests/Controller/RedirectToServiceControllerTest.php
tests/Functional/IntegrationTest.php
tests/Security/OAuthUtilsTest.php

If matched firewall does not have **oauth** listener/authenticator (aka login_area in old Symfony), the last `potentialResourceOwnerCheckPath` (basically from main firewall) will be taken. 
fixes #1885

Current matched Firewall is respected during generation of check path links.

---

src/DependencyInjection/Configuration.php

Fix typo in comment on how to register own resource owners

Fix typo in configuration comment

---

.github/workflows/ci.yaml
src/OAuth/ResourceOwner/AbstractResourceOwner.php
src/OAuth/ResourceOwner/DropboxResourceOwner.php
src/OAuth/ResourceOwnerInterface.php
src/Security/Core/Authentication/Token/AbstractOAuthToken.php

Fixes deprecation notice when running on PHP 8.2: `Deprecated: Use of "parent" in callables is deprecated`
Since we are requiring Symfony ^4.4, `__serialize()` is already there (since v4.3) so we don't need to check if it exists:
https://github.com/symfony/symfony/blob/c52b0edeb04feab571e2514ac8d613aed186d5ed/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L160-L182
Added PHP 8.2 to the build matrix too.
Failing style check is not related.

Fix PHP 8.2 compatibility

---

CHANGELOG.md

More over, it should have been `~6.0.0`

Avoid confusion about Symfony version support dropped

---

CHANGELOG.md
src/Security/Core/User/OAuthUserProvider.php

Prevent fatal error in `loadUserByOAuthUserResponse()` when `nickname` is not available in OAuth response

---

tests/Functional/IntegrationTest.php

Till there is new release with the fix from: https://github.com/symfony/symfony/pull/51350 we should skip testing for Symfony 6.

Temporary skip broken test on Symfony 6

---

CHANGELOG.md
src/Security/Core/Authentication/Token/AbstractOAuthToken.php

Prevent fatal error when token doesn't have resource owner name set

---

docs/2-configuring_resource_owners.md
docs/resource_owners/telegram.md
src/OAuth/ResourceOwner/TelegramResourceOwner.php
tests/OAuth/ResourceOwner/TelegramResourceOwnerTest.php

Sample config
```yaml
hwi_oauth:
resource_owners:
telegram:
type: telegram
client_id: NOT_REQUIRED # but required by bundle
client_secret: '%env(TG_BOT_TOKEN)%'
```

Add Telegram resource owner

---

docs/3-configuring_the_security_layer.md
src/Resources/config/oauth.php

Document how to configure entity provider

---

docs/3-configuring_the_security_layer.md

I am trying to reconfigure an app during a Symfony 5.4 -> 6.4 upgrade. During this, I took the time to realign my use of this bundle to the standard and the recipe.
I'm not using the connect feature, and I was unable to make it work until I added the suggested line to my access control, because without that the redirect route (`/connect/{service}`) is hidden behind the default rule (`^/ roles: ROLE_USER`) and hence triggering a loop that pushes me back to the login page.

Fix access control suggestions

---

CHANGELOG.md
src/DependencyInjection/Security/Factory/OAuthAuthenticatorFactory.php
src/Resources/config/oauth.php
src/Security/Http/Authentication/AuthenticationFailureHandler.php
src/Security/Http/Authenticator/OAuthAuthenticator.php
tests/Security/Http/Authentication/AuthenticationFailureHandlerTest.php

Prevent overwriting `failure_path` in `AuthenticationFailureHandler`

---

docs/resource_owners/auth0.md
src/OAuth/ResourceOwner/Auth0ResourceOwner.php
src/OAuth/ResourceOwner/KeycloakResourceOwner.php
tests/App/Form/RegistrationFormType.php
tests/App/ResourceOwner/CustomResourceOwner.php
tests/OAuth/ResourceOwner/KeycloakResourceOwnerTest.php
tests/Security/Http/RefreshOnExpireTest.php

Adds (optional) support for `organization` and `audience` options in the `Auth0ResourceOwner`. 
These parameters are required when an application is set up with a no-prompt business-user login flow:
This fixes https://github.com/hwi/HWIOAuthBundle/issues/1697.

Added support for optional audience and organization options for Auth0.

---

src/DependencyInjection/HWIOAuthExtension.php

Symfony 7.2 triggers a deprecation about the `Symfony\Component\HttpKernel\DependencyInjection\Extension` class. In order to get rid of that, I'm extending `Symfony\Component\DependencyInjection\Extension\Extension` now.
This is technically a BC break because our extension class won't pass an `instanceof` check for the deprecated class anymore, but I believe that this is acceptable.

Use non-deprecated Extension class

---

composer.json
src/Security/OAuthUtils.php
tests/Security/OAuthUtilsTest.php

Once upgraded my project to symfony 6.4 (particularly the http-foundation component), I've noticed that OAuthUtils started to throw exception if "state" parameter is passed as an array (this is the way we do it in my project atm). According to the http-foundation changelog:
> Retrieving non-scalar values using InputBag::get() will throw BadRequestException (use InputBad::all() instead to retrieve an array)
This behavior has been deprecated since v5.1 and removed in 6.0.
I've also added symfony/http-foundation as a direct dependency to the composer.json. I was not sure about it, but it's obvious that this bundle relates on the Request class from the http-foundation, but it wasn't present in composer.json for some reason.

Fixed array state for symfony/http-foundation >= 6.0

---

docs/3-configuring_the_security_layer.md

The path given here in the docs seems to refer to the old location for editing routing (Symfony 2 and 3). It will direct you to a nonexistent file on Symfony 4+. So I substituted it for the more up-to-date location to add these routes.

Corrected old path for editing routing

---

src/Security/Http/Firewall/RefreshAccessTokenListener.php

This is a re-do of #2020, with a workaround to avoid PHPStan errors, which was in fast highlighting a possible failure case.

Fix RefreshAccessTokenListener after Symfony 7.2 decoration

---

src/Security/Http/Firewall/AbstractRefreshAccessTokenListener.php

When creating a custom ResourceOwnerMap (for example, if you need to pull configs from the DB), an error appears in AbstractRefreshAccessTokenListener

fix AbstractRefreshAccessTokenListener

---

README.md
docs/2-configuring_resource_owners.md
docs/resource_owners/amazon_cognito.md
src/OAuth/ResourceOwner/AmazonCognitoResourceOwner.php
tests/OAuth/ResourceOwner/AmazonCognitoResourceOwnerTest.php

Integration with Amazon Cognito

Amazon Cognito integration

---

.github/workflows/ci.yaml
docs/resource_owners/spotify.md
src/OAuth/ResourceOwner/SpotifyResourceOwner.php
tests/OAuth/ResourceOwner/SpotifyResourceOwnerTest.php

Allow to set the optional "show_dialog" option for the Spotify resource owner: https://developer.spotify.com/documentation/web-api/tutorials/code-flow.
```
Whether or not to force the user to approve the app again if they’ve already done so. If false (default), a user who has already approved the application may be automatically redirected to the URI specified by redirect_uri. If true, the user will not be automatically redirected and will have to approve the app again.
```

Add option "show_dialog" for Spotify resource owner

---

src/Security/Helper/NonceGenerator.php

The current nonce generator is time based and predictable, use the PHP builtin cryptographically secure random byte generator instead.

Use CSPRNG for generating nonce

---

src/Controller/Connect/RegisterController.php

When using i.e., Turbo, it will cache the response when returning `200`; here, the form can be invalid, and we should return that as a proper HTTP status code in the response.
Ref: https://symfony.com/bundles/ux-turbo/current/index.html#3-form-response-code-changes

Fixed wrong HTTP status code in `RegisterController`
